//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "SOACommon_BaseServiceResponse.h"


@class SOACommon_ExtensionType;
@class FindingService_ConditionHistogramContainer;
@class FindingService_CategoryHistogramContainer;
@class FindingService_AspectHistogramContainer;

/**
 
 Response container for the getHistogram call. 
 
 
 @ingroup FindingService
*/
@interface FindingService_GetHistogramsResponse : SOACommon_BaseServiceResponse {

@private
    FindingService_CategoryHistogramContainer *categoryHistogramContainer;
    FindingService_AspectHistogramContainer *aspectHistogramContainer;
    FindingService_ConditionHistogramContainer *conditionHistogramContainer;
    NSMutableArray *extension;

}


/**
 
 Response container for category histograms. This container is
 returned only when the specified category has children categories.
 <br><br>
 <span class="tablenote"><strong>Note:</strong>
 Category histograms may not be available for some parent categories
 on the eBay Motors site.
 </span>
 
 
 type : class FindingService_CategoryHistogramContainer
*/
@property (nonatomic, retain) FindingService_CategoryHistogramContainer *categoryHistogramContainer;

/**
 
 Response container for aspect histograms. Aspect histograms are
 returned for categories that have been mapped to domains only. In
 most cases, just leaf categories are mapped to domains, but there are
 exceptions.
 
 
 type : class FindingService_AspectHistogramContainer
*/
@property (nonatomic, retain) FindingService_AspectHistogramContainer *aspectHistogramContainer;

/**
 
 Reserved for future use.
 
 
 type : class FindingService_ConditionHistogramContainer
*/
@property (nonatomic, retain) FindingService_ConditionHistogramContainer *conditionHistogramContainer;

/**
 
 Reserved for future use.
 
 
 entry type : class SOACommon_ExtensionType
*/
@property (nonatomic, retain) NSMutableArray *extension;


@end
