//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class FindingService_SearchItem;

/**
 
 Contains the returned item listings, if any. The data for each listing is
 returned in individual item containers.
 
 
 @ingroup FindingService
*/
@interface FindingService_SearchResult : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *item;
    NSString *delimiter;
    NSNumber *count;

}


/**
 
 Container for the data of a single item that matches the search criteria.
 
 
 entry type : class FindingService_SearchItem
*/
@property (nonatomic, retain) NSMutableArray *item;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *delimiter;


/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *count;


@end
