//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Contains details about a category. 
 
 
 @ingroup FindingService
*/
@interface FindingService_Category : NSObject <EbayNs_Bindable> {

@private
    NSString *categoryId;
    NSString *categoryName;

}


/**
 
 The unique ID of a category on the specified eBay site.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *categoryId;

/**
 
 Display name of a category as it appears on the eBay Web site. 
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *categoryName;


@end
