//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class FindingService_ConditionHistogram;

/**
 
 Reserved for future use.
 
 
 @ingroup FindingService
*/
@interface FindingService_ConditionHistogramContainer : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *conditionHistogram;
    NSString *delimiter;

}


/**
 
 Reserved for future use.
 
 
 entry type : class FindingService_ConditionHistogram
*/
@property (nonatomic, retain) NSMutableArray *conditionHistogram;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *delimiter;



@end
