//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "FindingService_BaseFindingServiceResponse.h"


@class FindingService_ConditionHistogramContainer;
@class FindingService_AspectHistogramContainer;

/**
 
 Response container for the findItemsByProduct call.
 
 
 @ingroup FindingService
*/
@interface FindingService_FindItemsByProductResponse : FindingService_BaseFindingServiceResponse {

@private
    FindingService_AspectHistogramContainer *aspectHistogramContainer;
    FindingService_ConditionHistogramContainer *conditionHistogramContainer;

}


/**
 
 Response container for aspect histograms.
 
 
 type : class FindingService_AspectHistogramContainer
*/
@property (nonatomic, retain) FindingService_AspectHistogramContainer *aspectHistogramContainer;

/**
 
 Reserved for future use.
 
 
 type : class FindingService_ConditionHistogramContainer
*/
@property (nonatomic, retain) FindingService_ConditionHistogramContainer *conditionHistogramContainer;


@end
