//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Container for details pertaining to individual aspect values, including their
 histogram information (item counts).
 
 
 @ingroup FindingService
*/
@interface FindingService_AspectValueHistogram : NSObject <EbayNs_Bindable> {

@private
    NSNumber *count;
    NSString *valueName;

}


/**
 
 Number of items that share the characteristic the respective aspect
 value.
 
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, retain) NSNumber *count;


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *valueName;


@end
