//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Shopping_AbstractRequestType.h"



/**
 
 Retrieves the words most frequently used by eBay users when searching for listings.
 These keywords are generated weekly by eBay. Thus, calls retrieve static data.
 FindPopularSearches is not available for the following sites: FR, HK, MY, PH, PL, SG, SE.
 
 
 @ingroup Shopping
*/
@interface Shopping_FindPopularSearchesRequestType : Shopping_AbstractRequestType {

@private
    NSMutableArray *categoryID;
    NSMutableArray *queryKeywords;
    NSNumber *maxKeywords;
    NSNumber *maxResultsPerPage;
    NSNumber *pageNumber;
    NSNumber *includeChildCategories;

}


/**
 
 Specify CategoryID to restrict your query to a specific category.
 Up to 10 categories may be specified
 If you are using a URL, and you want to specify
 multiple values, use a comma.
 For example, if you want to specify Fiction Books and
 Children's Books, specify CategoryID=377,279.
 <br>
 <br>
 If the specified category ID doesn't match an existing category
 for the site, an invalid-category error message is returned.
 To determine valid categories:<br>
 Use the FindItemsAdvanced CategoryHistogram value in the IncludeSelector field
 to retrieve matching categories. Then make another
 FindItemsAdvanced call with the ID of a matching category.
 <br>
 <br>
 CategoryID can be used in combination with QueryKeywords and IncludeChildCategories.
 When IncludeChildCategories is true and used in conjunction with CategoryID,
 one and only one CategoryID is allowed. Otherwise, up
 to 10 CategoryIDs are allowed.
 To retrieve the most popular keywords for a root category, set one of
 the CategoryIDs to -1 or do not include CategoryID in the Request.
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *categoryID;

/**
 
 A query that specifies a string for searching titles of items on eBay.
 If you are using a URL, then to search for multiple words,
 use "%20". For example, use Harry%20Potter to search for items
 containing those words in any order.
 You can incorporate wildcards into a multi-word search, as in the following: ap*%20ip*.
 The words "and" and "or" are treated like any other word. Only use "and",
 "or", or "the" if you are searching for listings containing these words.
 <br>
 <br>
 QueryKeywords can be used in combination with CategoryID and IncludeChildCategories.
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *queryKeywords;

/**
 
 The maximum number of keywords to be retrieved per category
 for this call.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *maxKeywords;

/**
 
 Specifies the maximum number of PopularSearchResults per page in
 the returned list. If not specified, the default returns 20 results per page.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *maxResultsPerPage;

/**
 
 Specifies the number of the page of data to return in the current call.
 Specify a positive value equal to or lower than the number of pages
 available (which you determine by examining the results of your initial request).
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *pageNumber;

/**
 
 If true, only one CategoryID can be specified, and keywords
 are returned for that category and its subcategories.
 When IncludeChildCategories is true and used in conjunction with
 CategoryID, one and only one CategoryID is allowed.
 <br>
 <br>
 If false, keywords are returned only for the categories
 identified by CategoryID. The default is false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *includeChildCategories;


@end
