//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Shopping_AbstractResponseType.h"


@class Shopping_SimpleItemType;

/**
 
 Response to request of GetMultipleItems.
 
 
 @ingroup Shopping
*/
@interface Shopping_GetMultipleItemsResponseType : Shopping_AbstractResponseType {

@private
    NSMutableArray *item;

}


/**
 
 Contains details for a listing (or multiple) listings that correspond to the item ID(s) specified in the request.
 
 
 entry type : class Shopping_SimpleItemType
*/
@property (nonatomic, retain) NSMutableArray *item;


@end
