//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Shopping_VATDetailsType;
@class Shopping_AddressType;

/**
 
   Displays the seller's information (in a business card format) 
   as part of the data returned in the GetSingleItem call if the 
   seller's SellerBusinessCodeType is set to 'Commercial'. Note 
   that this option is only available for sites that have 
   Business Seller options enabled.
 
 
 @ingroup Shopping
*/
@interface Shopping_BusinessSellerDetailsType : NSObject <EbayNs_Bindable> {

@private
    Shopping_AddressType *address;
    NSString *fax;
    NSString *email;
    NSString *additionalContactInformation;
    NSString *tradeRegistrationNumber;
    NSNumber *legalInvoice;
    NSString *termsAndConditions;
    Shopping_VATDetailsType *vatDetails;

}


/**
 
 Displays the Address of the seller (in a business card 
 format) as part of the data returned in the  
 GetSingleItem call if the seller's SellerBusinessCodeType
 is set to 'Commercial'. 
 
 
 type : class Shopping_AddressType
*/
@property (nonatomic, retain) Shopping_AddressType *address;

/**
 
 Displays the fax number of the seller (in a business card 
 format) as part of the data returned in the  
 GetSingleItem call if the seller's SellerBusinessCodeType 
 is set to 'Commercial'.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *fax;

/**
 
 Displays the email address of the seller (in a business 
 card format) as part of the data returned in the  
 GetSingleItem call if the seller's 
 SellerBusinessCodeType is set to 'Commercial'.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *email;

/**
 
 Displays the AdditionalContactInformation of the seller 
 (in a business card format) as part of the data returned 
 in the GetSingleItem call if the seller's 
 SellerBusinessCodeType is set to 'Commercial'. 
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *additionalContactInformation;

/**
 
 Displays the TradeRegistrationNumber of the seller (in a 
 business card format) as part of the data returned in the 
 GetSingleItem call if the seller's SellerBusinessCodeType 
 is set to 'Commercial'.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *tradeRegistrationNumber;

/**
 
 Displays the LegalInvoice of the seller (in a business card 
 format) as part of the data returned in the GetSingleItem 
 call if the seller's SellerBusinessCodeType is set to 
 'Commercial'.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *legalInvoice;

/**
 
 Displays the TermsAndConditions of the seller (in a business card 
 format) as part of the data returned in the GetSingleItem call 
 if the seller's SellerBusinessCodeType is set to 'Commercial'.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *termsAndConditions;

/**
 
 Displays the VATDetails of the seller (in a business card
 format) as part of the data returned in the GetSingleItem 
 call if the seller's SellerBusinessCodeType is set to 
 'Commercial'.
 
 
 type : class Shopping_VATDetailsType
*/
@property (nonatomic, retain) Shopping_VATDetailsType *vatDetails;



@end
