//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Shopping_AbstractResponseType.h"


@class Shopping_SimpleItemType;

/**
 
 Response to GetSingleItem request.
 
 
 @ingroup Shopping
*/
@interface Shopping_GetSingleItemResponseType : Shopping_AbstractResponseType {

@private
    Shopping_SimpleItemType *item;

}


/**
 
 Contains details about the listing whose ID was specified in
 the request.
 
 
 type : class Shopping_SimpleItemType
*/
@property (nonatomic, retain) Shopping_SimpleItemType *item;


@end
