//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Shopping_AbstractResponseType.h"


@class Shopping_SimpleItemArrayType;

/**
 
 Popular items, detail level is default for simple item type. addition with WatchCount.
 
 
 @ingroup Shopping
*/
@interface Shopping_FindPopularItemsResponseType : Shopping_AbstractResponseType {

@private
    Shopping_SimpleItemArrayType *itemArray;

}


/**
 
 A list of active items that were listed with the requested product.
 
 
 type : class Shopping_SimpleItemArrayType
*/
@property (nonatomic, retain) Shopping_SimpleItemArrayType *itemArray;


@end
