//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Shopping_BuyingGuideType;

/**
 
 Information about zero or more buying guides and the site's buying guide hub.
 Buying guides contain content about particular product areas, categories, or subjects
 to help buyers decide which type of item to purchase based on their particular interests.
 Multiple buying guides can be returned. See the eBay Web Services Guide for additional information.
 
 
 @ingroup Shopping
*/
@interface Shopping_BuyingGuideDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *buyingGuide;
    NSString *buyingGuideHub;

}


/**
 
 Information that identifies a buying guide. A buying guide contains content about particular
 product areas, categories, or subjects to help buyers decide which type of item
 to purchase based on their particular interests.
 Buying guides are useful to buyers who do not have a specific product in mind.
 For example, a digital camera buying guide could help a buyer determine what kind of
 digital camera is right for them.
 
 
 entry type : class Shopping_BuyingGuideType
*/
@property (nonatomic, retain) NSMutableArray *buyingGuide;

/**
 
 URL of the buying guide home page for the site being searched.
 Your application can present this URL as a link. Optionally,
 you can use a value like "See all buying guides" as the link's
 display name. 
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *buyingGuideHub;



@end
