//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Product ID has an attribute of ProductIDCodeType and a string value.
 
 
 @ingroup Shopping
*/
@interface Shopping_ProductIDType : NSObject <EbayNs_Bindable> {

@private
    NSString *value;
    NSString *type;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *value;

/**
 (public property)
 
 type: string constant in Shopping_ProductIDCodeType.h
*/
@property (nonatomic, retain) NSString *type;


@end
