//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Shopping_AbstractRequestType.h"



/**
 
 Contains a single ItemID or an array of ItemIDs.
 
 
 @ingroup Shopping
*/
@interface Shopping_GetItemStatusRequestType : Shopping_AbstractRequestType {

@private
    NSMutableArray *itemID;

}


/**
 
 The item ID that uniquely identifies the item listing for which to retrieve the data. You can provide a maximum of 20 ItemIDs. Use a comma to separate ItemIDs.
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *itemID;


@end
