//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class SOACommon_ExtensionType;
@class SOACommon_ErrorMessage;

/**
 
 Base response container for all service
 operations. Contains error information
 associated with the request.
 
 
 @ingroup DeviceConfigurationService
*/
@interface SOACommon_BaseResponse : NSObject <EbayNs_Bindable> {

@private
    NSString *ack;
    SOACommon_ErrorMessage *errorMessage;
    NSString *version;
    NSDate *timestamp;
    NSMutableArray *extension;

}


/**
 
                                 Indicates whether the error is a
         severe error (causing the request to
         fail) or an informational error (a
         warning) that should be communicated
         to the user.
 
 
 type: string constant in SOACommon_AckValue.h
*/
@property (nonatomic, retain) NSString *ack;

/**
 
 Information for an error or warning that
 occurred when eBay processed the
 request.
 
 
 type : class SOACommon_ErrorMessage
*/
@property (nonatomic, retain) SOACommon_ErrorMessage *errorMessage;

/**
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *version;

/**
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *timestamp;

/**
 (public property)
 
 entry type : class SOACommon_ExtensionType
*/
@property (nonatomic, retain) NSMutableArray *extension;


@end
