//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class SOACommon_ExtensionType;

/**
 
 This is the base class for request container for
 all service operations.
 
 
 @ingroup DeviceConfigurationService
*/
@interface SOACommon_BaseRequest : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *extension;

}


/**
 (public property)
 
 entry type : class SOACommon_ExtensionType
*/
@property (nonatomic, retain) NSMutableArray *extension;


@end
