//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"

// abstract class

@class SOACommon_ErrorMessage;

/**
 
 Base response container for all service operations. Contains error
 information associated with the request.
 
 
 @ingroup FindingService
*/
@interface SOACommon_BaseServiceResponse : NSObject <EbayNs_Bindable> {

@private
    NSString *ack;
    SOACommon_ErrorMessage *errorMessage;
    NSString *version;
    NSDate *timestamp;

}


/**
 
 Indicates whether or not errors or warnings were generated during the
 processing of the request.
 
 
 type: string constant in SOACommon_AckValue.h
*/
@property (nonatomic, retain) NSString *ack;

/**
 
 Description of an error or warning that occurred when eBay processed the
 request. Not returned if the ack value is Success.
 
 
 type : class SOACommon_ErrorMessage
*/
@property (nonatomic, retain) SOACommon_ErrorMessage *errorMessage;

/**
 
 The release version that eBay used to process the request. Developer
 Technical Support may ask you for the version value if you work with them
 to troubleshoot issues.
 <br><br>
 <span class="tablenote"><strong>Note:</strong>
 The version in use is normally the latest release version, as specified
 in the release notes. Note that eBay releases the API to international
 sites about a week after the API version is released to the US site.
 </span>
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *version;

/**
 
 This value represents the date and time when eBay processed the request.
 This value is returned in GMT, the ISO 8601 date and time format (YYYY-
 MM- DDTHH:MM:SS.SSSZ). See the "dateTime" type for information about the
 time format, and for details on converting to and from the GMT time zone.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *timestamp;


@end
