//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>


/**
 
 Sorts items by Best Match, and no sort order applies. If specified, 
 then Best Match sort also applies to CategoryHistogram.
 
*/
extern NSString *const Trading_SimpleItemSortCodeType_BEST_MATCH;

/**
 
 Placeholder value. See
 <a href="types/simpleTypes.html#token">token</a>.
 
*/
extern NSString *const Trading_SimpleItemSortCodeType_CUSTOM_CODE;

/**
 
 Sorts items by end time in ascending or descending order.
 
*/
extern NSString *const Trading_SimpleItemSortCodeType_END_TIME;

/**
 
 Sort by number of bids on the item in ascending or descending order.
 
*/
extern NSString *const Trading_SimpleItemSortCodeType_BID_COUNT;

/**
 
 Sort by country; no sort order can be specified.
 
*/
extern NSString *const Trading_SimpleItemSortCodeType_COUNTRY;

/**
 
 Sort by current bid; descending order only.
 
*/
extern NSString *const Trading_SimpleItemSortCodeType_CURRENT_BID;

/**
 
 Sort by distance, ascending order only.
 
*/
extern NSString *const Trading_SimpleItemSortCodeType_DISTANCE;

/**
 
 Sort by start date, recently-listed first.
 
*/
extern NSString *const Trading_SimpleItemSortCodeType_START_DATE;

/**
 
 (in) Sort by BestMatchCategoryGroup, so results are grouped by Best Match within a category.
 
*/
extern NSString *const Trading_SimpleItemSortCodeType_BEST_MATCH_CATEGORY_GROUP;

/**
 
 (in) This value is part of the Price Plus Shipping Sort feature, to be enabled
 by the end of Sept. 2007 for the following sites:
 US (site ID 0), Germany (77), Canada (2), and Australia (15).
 The Price Plus Shipping Sort feature causes item sorting to consider shipping costs.
 Specify PricePlusShippingAsc to sort items by lowest cost first, as follows:
 Lowest-total-cost (for items where shipping was properly specified), 
 then freight-shipping items, then items for which shipping was not specified (sorted by price).
 
*/
extern NSString *const Trading_SimpleItemSortCodeType_PRICE_PLUS_SHIPPING;
  
