//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Indicates whether counter offers are allowed on best offers for this category.
 Returned only if this category overrides the site default.
 Added for Local Market users.
 
 
 @ingroup Trading
*/
@interface Trading_LocalMarketCounterOfferEnabledDefinitionType : NSObject <EbayNs_Bindable> {

@private

}




@end
