//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_NameValueListArrayType;

/**
 
 Used to provide input for ItemID and VariationSpecific
 
 
 @ingroup Trading
*/
@interface Trading_VariationKeyType : NSObject <EbayNs_Bindable> {

@private
    NSString *itemID;
    Trading_NameValueListArrayType *variationSpecifics;

}


/**
 
 The ID of the item whose variation(s) should be added to or 
 removed from the watch list.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *itemID;

/**
 
 Name-value pairs that identify a variation within the 
 listing identified by VariationKey.ItemID. 
 or that partially match one or more variations. Names may not be duplicated in the same VariationSpecifics container. 
 If the specified pairs do not match any variation, the call
 behaves as if no variations were specified.
 
 
 type : class Trading_NameValueListArrayType
*/
@property (nonatomic, retain) Trading_NameValueListArrayType *variationSpecifics;



@end
