//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Specifies the details of policy violations if the item was administratively canceled.
 The details are the policy ID and the policy text.
 
 
 @ingroup Trading
*/
@interface Trading_ItemPolicyViolationType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *policyID;
    NSString *policyText;

}


/**
 
 Policy ID of the violated policy which resulted in item being administratively canceled.
 
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, retain) NSNumber *policyID;

/**
 
 Brief information of the violated policy which resulted in item being administratively canceled.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *policyText;



@end
