//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 [Selling] Details of the maximum number of unpaid item strikes.
 
 
 @ingroup Trading
*/
@interface Trading_MaximumUnpaidItemStrikesCountDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *count;

}


/**
 
 [Selling] Number of allowed unpaid item strikes against the buyer.
 
 
 entry type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSMutableArray *count;



@end
