//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
   Contains a seller's preference for sending a "Payment Reminder Email" to buyers.
 
 
 @ingroup Trading
*/
@interface Trading_PurchaseReminderEmailPreferencesType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *purchaseReminderEmailPreferences;

}


/**
 
   If true, a purchase reminder email is sent to buyers.
   In My eBay, a seller can decide whether a "payment reminder email,"
   reminding to buyers to pay for a purchase, is sent.
   
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *purchaseReminderEmailPreferences;



@end
