//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Packages supported by the enclosing shipping service.
 
 
 @ingroup Trading
*/
@interface Trading_ShippingServicePackageDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSString *name;
    NSNumber *dimensionsRequired;

}


/**
 
 The name of the package type.
 
 
 type: string constant in Trading_ShippingPackageCodeType.h
*/
@property (nonatomic, retain) NSString *name;

/**
 
 This is a characteristic of a package type in the context of a particular shipping service.
 If true, dimensions are required when this particular package type is assigned to the
 listing and the seller offers this particular shipping service.
 If not returned, DimensionsSupported is false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *dimensionsRequired;



@end
