//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
   Defines settings for a notification URL (including the URL name in DeliveryURLName).
 
 
 @ingroup Trading
*/
@interface Trading_DeliveryURLDetailType : NSObject <EbayNs_Bindable> {

@private
    NSString *deliveryURLName;
    NSString *deliveryURL;
    NSString *status;

}


/**
 
 The name of a notification delivery URL. 
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *deliveryURLName;

/**
 
 The address of a notification delivery URL.
 This address applies to the DeliveryURLName
 within the same
 ApplicationDeliveryPreferences.DeliveryURLDetails container.
 For delivery to a server, the URL
 begins with http:// or https:// and must be well
 formed. Use a URL that is functional at the time of the
 call. For delivery to an email address, the URL begins
 with mailto: and specifies a valid email address.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *deliveryURL;

/**
 
 The status of a notification delivery URL.
 This status applies to the DeliveryURLName and delivery URL
 within the same ApplicationDeliveryPreferences.DeliveryURLDetails container.
         If the status is disabled, then notifications will not be sent to the delivery URL.
 
 
 type: string constant in Trading_EnableCodeType.h
*/
@property (nonatomic, retain) NSString *status;



@end
