//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Indicates whether automatic decline of best offers is allowed for this category.
 Returned only if this category overrides the site default.
 Added for Local market users.
 
 
 @ingroup Trading
*/
@interface Trading_LocalMarketAutoDeclineEnabledDefinitionType : NSObject <EbayNs_Bindable> {

@private

}




@end
