//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Specifies a predefined subset of item conditions. The predefined set of fields
 can vary for different calls.
 
 
 @ingroup Trading
*/

/**
 
 The seller specified the Item Condition as New, or
 did not specify a condition.
 (Excludes items that the seller listed as Used.)
 
*/
extern NSString *const Trading_ItemConditionCodeType_NEW;

/**
 
 The seller specified the Item Condition as Used, or
 did not specify a condition.
 (Excludes items that the seller listed as New.)
 
*/
extern NSString *const Trading_ItemConditionCodeType_USED;

/**
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_ItemConditionCodeType_CUSTOM_CODE;
  
