//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
  
 Not applicable to any site. Formerly applicable to the
 Australia site (site ID 15, abbreviation AU) only.
 
 
 @ingroup Trading
*/
@interface Trading_BasicUpgradePackEnabledDefinitionType : NSObject <EbayNs_Bindable> {

@private

}




@end
