//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 (public class)
 
 @ingroup Trading
*/
@interface Trading_ExtendedProductFinderIDType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *productFinderID;
    NSNumber *productFinderBuySide;

}


/**
 
 A product finder ID. GetCategory2CS always (and only) returns this
 when Category.ProductFinderIDs is returned.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *productFinderID;

/**
 
 If false or not present, the product finder can be used as input to
 GetProductSearchResults to search for catalog data (Pre-filled Item Information)
 that a seller might want to include in a listing.<br>
 <br>
 If true, the product finder can be used as input to GetSearchResults
 to search for listings with Item Specifics on the eBay site. However,
 if you have trouble using the specified product finder with GetSearchResults,
 or if you can't find a product finder ID that you saw on the Web site,
 here is a workaround: Use the pfid parameter from the URL of the 
 Product Finder search page on the site you're interested in. 
 See the Knowledge Base article referenced below for more details.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *productFinderBuySide;


@end
