//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 (public class)
 
 @ingroup Trading
*/
@interface Trading_SearchDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *buyItNowEnabled;
    NSNumber *picture;
    NSNumber *recentListing;

}


/**
 
 Indicates whether a listing uses the Buy It Now feature.
 For GetProducts, only returned for listing types that support
 Buy It Now (like Chinese auctions.)
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *buyItNowEnabled;

/**
 
           Indicates whether a listing has an image associated with it.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *picture;

/**
 
 Indicates whether a listing is no more than one day old.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *recentListing;



@end
