//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Details relating to a My Messages folder.
 
 
 @ingroup Trading
*/
@interface Trading_MyMessagesFolderType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *folderID;
    NSString *folderName;

}


/**
 
 An ID that uniquely identifies a My Messages folder.
 
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, retain) NSNumber *folderID;

/**
 
 The name of a specified My Messages folder.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *folderName;



@end
