//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Used to indicate whether the parts compatibility feature is enabled for a 
 category.
 <br><br> 
 Parts Compatibility is supported in limited Parts & Accessories
 categories for the eBay Motors (US) site (site ID 100) only.
 
 
 @ingroup Trading
*/

/**
 
 Parts Compatibility is not supported for the given category.
 
*/
extern NSString *const Trading_ItemCompatibilityEnabledCodeType_DISABLED;

/**
 
 Parts Compatibility may be entered by application only for the given category.
 Entering parts compatibility by application specifies the assemblies (e.g., a
 specific year, make, and model of car) to which the item applies. Parts
 compatibility by application can be specified by listing with a catalog
 product that supports parts compatibility or by specifying parts compatibility
 by application manually (<b 
 class="con"> Item.ItemCompatibilityList</b>).
 
*/
extern NSString *const Trading_ItemCompatibilityEnabledCodeType_BY_APPLICATION;

/**
 
 Parts Compatibility may be entered by specification only for the given
 category. Entering parts compatibility by specification involves specifying
 the part's relevant dimensions or characteristics (e.g., Section Width, Aspect
 Ratio, Rim Diammeter, Load Index, and Speed Rating values for a tire) using
 attributes.
 
*/
extern NSString *const Trading_ItemCompatibilityEnabledCodeType_BY_SPECIFICATION;

/**
 
 (out) Reserved for internal or future use.
   
*/
extern NSString *const Trading_ItemCompatibilityEnabledCodeType_CUSTOM_CODE;
  
