//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_OrderType;

/**
 
 An array of Orders.
 
 
 @ingroup Trading
*/
@interface Trading_OrderArrayType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *order;

}


/**
 
 Also applicable to Half.com.
 
 
 entry type : class Trading_OrderType
*/
@property (nonatomic, retain) NSMutableArray *order;


@end
