//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AmountType;

/**
 
 Contains information about a single refund. A refund contains information
 about the amount refunded for a transaction to a single buyer. This refund
 contains information about the amount refunded from seller, refunded time
 and total amount refunded to buyer (amount from seller + half)
 
 
 @ingroup Trading
*/
@interface Trading_RefundType : NSObject <EbayNs_Bindable> {

@private
    Trading_AmountType *refundFromSeller;
    Trading_AmountType *totalRefundToBuyer;
    NSDate *refundTime;

}


/**
 
 Total amount refunded by the seller for this transaction.
 Applicable to Half.com (for GetOrders).
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *refundFromSeller;

/**
 
 Total amount refunded to the buyer for this transaction.
 Applicable to Half.com (for GetOrders).
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *totalRefundToBuyer;

/**
 
 The date and time at which the refund was issued. Applicable to Half.com (for GetOrders).
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *refundTime;



@end
