//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 PromotionItemPriceTypeCodeType - Type declaration to be used by other schema.
 Indicates the type of offer that can be made for a cross-promoted item. Note that
 for a Chinese listing with a still-active Buy It Now option, either a Bid
 (Auction) or a Buy It Now type offer may be made.
 
 
 @ingroup Trading
*/

/**
 
 (out) Bid offer in a competitive-bidding listing.
 
*/
extern NSString *const Trading_PromotionItemPriceTypeCodeType_AUCTION_PRICE;

/**
 
 (out) Buy It Now offer in a fixed-price or Buy It Now listing.
 
*/
extern NSString *const Trading_PromotionItemPriceTypeCodeType_BUY_IT_NOW_PRICE;

/**
 
 (out) Best Offer in Best Offer Only listing.
 
*/
extern NSString *const Trading_PromotionItemPriceTypeCodeType_BEST_OFFER_ONLY_PRICE;

/**
 
 (out) Advertised price for a Classified Ad format listing.
 
*/
extern NSString *const Trading_PromotionItemPriceTypeCodeType_CLASSIFIED_AD_PRICE;

/**
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_PromotionItemPriceTypeCodeType_CUSTOM_CODE;
  
