//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_StoreCustomCategoryType;

/**
 
   Set of custom categories for the Store.
   
 
 @ingroup Trading
*/
@interface Trading_StoreCustomCategoryArrayType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *customCategory;

}


/**
 
   A custom category for your eBay Store.
   
 
 entry type : class Trading_StoreCustomCategoryType
*/
@property (nonatomic, retain) NSMutableArray *customCategory;


@end
