//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Indicates whether Contact Seller is enabled for Classified Ads.
 Added for EbayMotors Pro users.
 
 
 @ingroup Trading
*/
@interface Trading_EBayMotorsProBestOfferEnabledDefinitionType : NSObject <EbayNs_Bindable> {

@private

}




@end
