//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Details about ProStores and checkout preferences.
 
 
 @ingroup Trading
*/
@interface Trading_ProStoresCheckoutPreferenceType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *checkoutRedirectProStores;

}


/**
 
 Indicates whether third party checkout is to be redirected to
 the ProStores application specified via My eBay preferences.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *checkoutRedirectProStores;



@end
