//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Contains the seller's preferences for the end of auction (EOA) email to the buyer.
 
 
 @ingroup Trading
*/
@interface Trading_EndOfAuctionEmailPreferencesType : NSObject <EbayNs_Bindable> {

@private
    NSString *templateText;
    NSString *logoURL;
    NSString *logoType;
    NSNumber *emailCustomized;
    NSNumber *textCustomized;
    NSNumber *logoCustomized;
    NSNumber *copyEmail;

}


/**
 
 The text of the custom message for the end of auction (for auctions) or end of
 transaction (for Buy It Now) emails.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *templateText;

/**
 
 The URL of the logo to include in the customized email.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *logoURL;

/**
 
 The type of logo to include in the customized email.
 
 
 type: string constant in Trading_EndOfAuctionLogoTypeCodeType.h
*/
@property (nonatomic, retain) NSString *logoType;

/**
 
 Indicates whether or not the seller wishes to send a customized email to winning buyers.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *emailCustomized;

/**
 
 Indicates whether or not the text of the customized message will be customized.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *textCustomized;

/**
 
 Indicates whether or not the seller wishes to include a logo in the customized email.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *logoCustomized;

/**
 
 Indicates whether or not the seller wishes to receive a copy of the customized
 email sent to the winning buyer.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *copyEmail;



@end
