//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Trading_AbstractResponseType.h"


@class Trading_FlatShippingDiscountType;
@class Trading_ShippingInsuranceType;
@class Trading_CalculatedHandlingDiscountType;
@class Trading_PromotionalShippingDiscountDetailsType;
@class Trading_CalculatedShippingDiscountType;

/**
 
 Response to call of GetShippingDiscountProfiles.
 
 
 @ingroup Trading
*/
@interface Trading_GetShippingDiscountProfilesResponseType : Trading_AbstractResponseType {

@private
    NSString *currencyID;
    Trading_FlatShippingDiscountType *flatShippingDiscount;
    Trading_CalculatedShippingDiscountType *calculatedShippingDiscount;
    NSNumber *promotionalShippingDiscount;
    Trading_CalculatedHandlingDiscountType *calculatedHandlingDiscount;
    Trading_PromotionalShippingDiscountDetailsType *promotionalShippingDiscountDetails;
    Trading_ShippingInsuranceType *shippingInsurance;
    Trading_ShippingInsuranceType *internationalShippingInsurance;
    NSString *combinedDuration;

}


/**
 
 The ID of the currency to be used for shipping cost discounts and
 insurance for combined payment. A discount profile can only be associated
 with a listing if the currency ID of the profile matches the currency ID
 of the listing.
 
 
 type: string constant in Trading_CurrencyCodeType.h
*/
@property (nonatomic, retain) NSString *currencyID;

/**
 
 Details of an individual discount profile defined by the
 user for flat rate shipping--one for each profile defined by the user.
 Empty if no shipping discount profiles were defined.
 
 
 type : class Trading_FlatShippingDiscountType
*/
@property (nonatomic, retain) Trading_FlatShippingDiscountType *flatShippingDiscount;

/**
 
 Details of an individual discount profile defined by the
 user for calculated shipping--one for each profile defined by the user.
 Empty if no shipping discount profiles were defined.
 
 
 type : class Trading_CalculatedShippingDiscountType
*/
@property (nonatomic, retain) Trading_CalculatedShippingDiscountType *calculatedShippingDiscount;

/**
 
 Indicates whether the user defined a promotional discount (the discount is active
 as soon as it exists).
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *promotionalShippingDiscount;

/**
 
 The data for the specific packaging/handling details for combined payment.
 Returned only if it has been defined.
 
 
 type : class Trading_CalculatedHandlingDiscountType
*/
@property (nonatomic, retain) Trading_CalculatedHandlingDiscountType *calculatedHandlingDiscount;

/**
 
 The data for the specific promotional shipping discount.
 Returned only if it has been defined.
 
 
 type : class Trading_PromotionalShippingDiscountDetailsType
*/
@property (nonatomic, retain) Trading_PromotionalShippingDiscountDetailsType *promotionalShippingDiscountDetails;

/**
 
 The data for the domestic insurance for combined payment.
 Returned only if it has been defined.
 
 
 type : class Trading_ShippingInsuranceType
*/
@property (nonatomic, retain) Trading_ShippingInsuranceType *shippingInsurance;

/**
 
 The data for the international insurance for combined payment.
 Returned only if it has been defined.
 
 
 type : class Trading_ShippingInsuranceType
*/
@property (nonatomic, retain) Trading_ShippingInsuranceType *internationalShippingInsurance;

/**
 
 Only those items purchased within CombinedDuration days of each other can
 be combined into an order and benefit from any shipping discounts.
 
 
 type: string constant in Trading_CombinedPaymentPeriodCodeType.h
*/
@property (nonatomic, retain) NSString *combinedDuration;


@end
