//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AttributeType;

/**
 
 Reserved for future use.
 
 
 @ingroup Trading
*/
@interface Trading_AttributeArrayType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *attribute;

}


/**
 
 Only applicable to Half.com. Not applicable to eBay listings.
 You can revise this field for Half.com listings.
 
 
 entry type : class Trading_AttributeType
*/
@property (nonatomic, retain) NSMutableArray *attribute;


@end
