//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
          Identifies a shipping carrier.
 
 
 @ingroup Trading
*/

/**
 
 United Parcel Service.
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_UPS;

/**
 
 U.S. Postal Service.
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_USPS;

/**
 
 Deutsche Post.
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_DEUTSCHE_POST;

/**
 
 DHL service
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_DHL;

/**
 
 Hermes
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_HERMES;

/**
 
 iLoxx
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_I_LOXX;

/**
 
 Other postal service
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_OTHER;

/**
 
 Coliposte Domestic
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_COLIPOSTE_DOMESTIC;

/**
 
 Coliposte International
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_COLIPOSTE_INTERNATIONAL;

/**
 
 Chronopost
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_CHRONOPOST;

/**
 
 Correos
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_CORREOS;

/**
 
 Seur (reserved for future use)
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_SEUR;

/**
 
 Nacex
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_NACEX;

/**
 
 Reserved for internal or future use
 
*/
extern NSString *const Trading_ShippingCarrierCodeType_CUSTOM_CODE;
  
