//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AmountType;

/**
 
 Details of a promotional shipping discount.
 
 
 @ingroup Trading
*/
@interface Trading_PromotionalShippingDiscountDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSString *discountName;
    Trading_AmountType *shippingCost;
    Trading_AmountType *orderAmount;
    NSNumber *itemCount;

}


/**
 
 The type of promotional shipping discount that is detailed in the profile.
 If MaximumShippingCostPerOrder, see ShippingCost.
 If ShippingCostXForAmountY, see ShippingCost and OrderAmount.
 If ShippingCostXForItemCountN, see ShippingCost and ItemCount.
 
 
 type: string constant in Trading_DiscountNameCodeType.h
*/
@property (nonatomic, retain) NSString *discountName;

/**
 
 This is shipping cost X, when DiscountName is either ShippingCostXForAmountY or
 ShippingCostXForItemCountN, and is the maximum cost when DiscountName is
 MaximumShippingCostPerOrder.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *shippingCost;

/**
 
 This is the cost Y of the order (not including shipping cost),
 when DiscountName is set to ShippingCostXForAmountY.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *orderAmount;

/**
 
 This is the number of items, when DiscountName is set to ShippingCostXForItemsY.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *itemCount;



@end
