//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Specifies 1 year feedback metrics as buyer.
 
 
 @ingroup Trading
*/
@interface Trading_BuyerRoleMetricsType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *positiveFeedbackLeftCount;
    NSNumber *negativeFeedbackLeftCount;
    NSNumber *neutralFeedbackLeftCount;
    NSNumber *feedbackLeftPercent;

}


/**
 
 Count of positive feedback entries given as a buyer.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *positiveFeedbackLeftCount;

/**
 
 Count of negative feedback entries given as a buyer.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *negativeFeedbackLeftCount;

/**
 
 Count of neutral feedback entries given as a buyer.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *neutralFeedbackLeftCount;

/**
 
 Percentage of leaving feedback as a buyer.
 
 
 type : NSNumber, wrapper for primitive float
*/
@property (nonatomic, retain) NSNumber *feedbackLeftPercent;



@end
