//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_ConditionType;

/**
 
 Fields in this type provide condition values and display names.
 
 
 @ingroup Trading
*/
@interface Trading_ConditionValuesType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *condition;
    NSString *conditionHelpURL;

}


/**
 
 Defines an item condition that a category supports.
 
 
 entry type : class Trading_ConditionType
*/
@property (nonatomic, retain) NSMutableArray *condition;

/**
 
 URL to the eBay Web site's item condition help for the 
 category. This may include policies about how to assess the 
 condition of an item in the category. To reduce 
 item-not-as-described disputes, we recommend that 
 you refer sellers (and buyers) to these help pages.
 These help pages may vary for some categories.<br>
 <br>
 The Sandbox might not return valid help URLs.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *conditionHelpURL;



@end
