//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Container for the list of locations to where the seller will not ship items.
 
 
 @ingroup Trading
*/
@interface Trading_SellerExcludeShipToLocationPreferencesType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *excludeShipToLocation;

}


/**
 
 Code denoting a location to where the seller will not ship.
 <br>
 The codes reflect the <a href=
 "http://www.iso.org/iso/country_codes/iso_3166_code_lists/english_country_names_and_code_elements.htm"
 >ISO 3166</a> location codes.
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *excludeShipToLocation;



@end
