//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_ItemType;
@class Trading_BestOfferArrayType;

/**
 
 All best offers for the item according to the filter or best offer
 id (or both) used in the input.
 For the notification client usage, this response includes a
 single Best Offer.
 
 
 @ingroup Trading
*/
@interface Trading_ItemBestOffersType : NSObject <EbayNs_Bindable> {

@private
    NSString *role;
    Trading_BestOfferArrayType *bestOfferArray;
    Trading_ItemType *item;

}


/**
 
 Indicates whether the user who was the feedback recipient was a Buyer or the
 Seller for that transaction.
 
 
 type: string constant in Trading_TradingRoleCodeType.h
*/
@property (nonatomic, retain) NSString *role;

/**
 
 All best offers for the item according to the filter or
 best offer id (or both) used in the input. The buyer and
 seller messages are returned only if the detail level is
 defined. Includes the buyer and seller message only if
 detail level ReturnAll is used.
 Only returned if best offers have been made.
 
 
 type : class Trading_BestOfferArrayType
*/
@property (nonatomic, retain) Trading_BestOfferArrayType *bestOfferArray;

/**
 
 The item for which Best Offers are being returned.
 Only returned if best offers have been made.
 
 
 type : class Trading_ItemType
*/
@property (nonatomic, retain) Trading_ItemType *item;



@end
