//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
  
 Defines the escrow workflow version applicable for the given category on the India site, if the category
 supports PaisaPayFullEscrow. If this field is present, the corresponding feature applies to the category. 
 The fieldis returned as an empty element. 
 
 
 @ingroup Trading
*/
@interface Trading_INEscrowWorkflowTimelineDefinitionType : NSObject <EbayNs_Bindable> {

@private

}




@end
