//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_FeedbackPeriodArrayType;
@class Trading_SellerRatingSummaryArrayType;
@class Trading_SellerRoleMetricsType;
@class Trading_BuyerRoleMetricsType;

/**
 
 Specifies all feedback summary information (except Score). Contains
 FeedbackPeriodArrayType objects that each convey feedback counts for positive,
 negative, neutral, and total feedback counts - for various time periods each. Also
 conveys counts of bid retractions for the predefined time periods.
 
 
 @ingroup Trading
*/
@interface Trading_FeedbackSummaryType : NSObject <EbayNs_Bindable> {

@private
    Trading_FeedbackPeriodArrayType *bidRetractionFeedbackPeriodArray;
    Trading_FeedbackPeriodArrayType *negativeFeedbackPeriodArray;
    Trading_FeedbackPeriodArrayType *neutralFeedbackPeriodArray;
    Trading_FeedbackPeriodArrayType *positiveFeedbackPeriodArray;
    Trading_FeedbackPeriodArrayType *totalFeedbackPeriodArray;
    NSNumber *neutralCommentCountFromSuspendedUsers;
    NSNumber *uniqueNegativeFeedbackCount;
    NSNumber *uniquePositiveFeedbackCount;
    NSNumber *uniqueNeutralFeedbackCount;
    Trading_SellerRatingSummaryArrayType *sellerRatingSummaryArray;
    Trading_SellerRoleMetricsType *sellerRoleMetrics;
    Trading_BuyerRoleMetricsType *buyerRoleMetrics;

}


/**
 
 Bid retractions count, for multiple predefined time periods preceding
 the call. Returned if no detail level is specified.
 
 
 type : class Trading_FeedbackPeriodArrayType
*/
@property (nonatomic, retain) Trading_FeedbackPeriodArrayType *bidRetractionFeedbackPeriodArray;

/**
 
 Negative feedback entries count, for multiple predefined time periods preceding
 the call. Returned if no detail level is specified.
 
 
 type : class Trading_FeedbackPeriodArrayType
*/
@property (nonatomic, retain) Trading_FeedbackPeriodArrayType *negativeFeedbackPeriodArray;

/**
 
 Neutral feedback entries count, for multiple predefined time periods preceding
 the call. Returned if no detail level is specified.
 
 
 type : class Trading_FeedbackPeriodArrayType
*/
@property (nonatomic, retain) Trading_FeedbackPeriodArrayType *neutralFeedbackPeriodArray;

/**
 
 Positive feedback entries count, for multiple predefined time periods
 preceding the call. Returned if no detail level is specified.
 
 
 type : class Trading_FeedbackPeriodArrayType
*/
@property (nonatomic, retain) Trading_FeedbackPeriodArrayType *positiveFeedbackPeriodArray;

/**
 
 Total feedback score, for multiple predefined time periods preceding the
 call. Returned if no detail level is specified.
 
 
 type : class Trading_FeedbackPeriodArrayType
*/
@property (nonatomic, retain) Trading_FeedbackPeriodArrayType *totalFeedbackPeriodArray;

/**
 
 Number of neutral comments received from suspended users. Returned if no
 detail level is specified.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *neutralCommentCountFromSuspendedUsers;

/**
 
 Total number of negative Feedback comments, including weekly repeats. Returned if no detail level is specified.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *uniqueNegativeFeedbackCount;

/**
 
 Total number of positive Feedback comments, including weekly repeats. Returned if no detail level is specified.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *uniquePositiveFeedbackCount;

/**
 
 Total number of neutral Feedback comments, including weekly repeats. Returned if no detail level is specified.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *uniqueNeutralFeedbackCount;

/**
 
 Container for information about detailed seller ratings (DSRs)
 that buyers have left for a seller.
 Sellers have access to the number of ratings they've received, as well as
 to the averages of DSRs they've received in each
 DSR area (i.e., to the average of ratings in the item-description area, etc.).
 The DSR feature is available on the United Kingdom site
 and on the following other sites: AU (site ID 15), BEFR (site ID 23),
 BENL (site ID 123), FR (site ID 71), IE (site ID 205), IN (site ID 203),
 IT (site ID 101), and PL (site ID 212). The DSR feature is available on the other
 API-enabled country sites, including the US site (site ID 0).
 
 
 type : class Trading_SellerRatingSummaryArrayType
*/
@property (nonatomic, retain) Trading_SellerRatingSummaryArrayType *sellerRatingSummaryArray;

/**
 
 Container for information about 1 year feedback metric as seller.
 
 
 type : class Trading_SellerRoleMetricsType
*/
@property (nonatomic, retain) Trading_SellerRoleMetricsType *sellerRoleMetrics;

/**
 
 Container for information about 1 year feedback metric as buyer.
 
 
 type : class Trading_BuyerRoleMetricsType
*/
@property (nonatomic, retain) Trading_BuyerRoleMetricsType *buyerRoleMetrics;



@end
