//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Details about a region or location to which the seller is willing to ship.
 
 
 @ingroup Trading
*/
@interface Trading_ShippingLocationDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSString *shippingLocation;
    NSString *description;
    NSString *detailVersion;
    NSDate *updateTime;

}


/**
 
 Short name or abbreviation for a region (e.g., Asia) or location (e.g. Japan).<br><br>
 Related field:<br>
 Item.ShippingDetails.InternationalShippingServiceOption.ShipToLocation in AddItem
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *shippingLocation;

/**
 
 Display name of region or location (sometimes more descriptive than the
 ShippingLocation short name).
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *description;

/**
 
 Returns the latest version number for this field. The version can be
 used to determine if and when to refresh cached client data.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *detailVersion;

/**
 
 Gives the time in GMT that the feature flags for the details were last
 updated. This timestamp can be used to determine if and when to refresh
 cached client data.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *updateTime;



@end
