//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_TransactionType;

/**
 
 Contains an array of transactions.
 
 
 @ingroup Trading
*/
@interface Trading_TransactionArrayType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *transaction;

}


/**
 
 Information about one transaction.
 Also applicable to Half.com (for GetOrders).
 
 
 entry type : class Trading_TransactionType
*/
@property (nonatomic, retain) NSMutableArray *transaction;


@end
