//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Information used to add a feedback note for a user.
 
 
 @ingroup Trading
*/
@interface Trading_FeedbackInfoType : NSObject <EbayNs_Bindable> {

@private
    NSString *commentText;
    NSString *commentType;
    NSString *targetUser;

}


/**
 
 Textual comment that explains, clarifies, or justifies the feedback
 rating specified in CommentType. Still displayed if feedback is withdrawn.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *commentText;

/**
 
 Rating of the feedback being left (e.g., Positive). Sellers cannot leave neutral or negative feedback for buyers.
 
 
 type: string constant in Trading_CommentTypeCodeType.h
*/
@property (nonatomic, retain) NSString *commentType;

/**
 
 Recipient user for whom the feedback is being left.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *targetUser;



@end
