//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 (public class)
 
 @ingroup Trading
*/
@interface Trading_CheckoutStatusType : NSObject <EbayNs_Bindable> {

@private
    NSString *eBayPaymentStatus;
    NSDate *lastModifiedTime;
    NSString *paymentMethod;
    NSString *status;
    NSNumber *integratedMerchantCreditCardEnabled;

}


/**
 
 Indicates the success or failure of a buyer's online payment.
 Also applicable to Half.com (for GetOrders).
 
 
 type: string constant in Trading_PaymentStatusCodeType.h
*/
@property (nonatomic, retain) NSString *eBayPaymentStatus;

/**
 
 The time the status was last modified.
 Also applicable to Half.com (for GetOrders).
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *lastModifiedTime;

/**
 
 The payment method the buyer uses when paying for the order.
 Note that the individual transactions may specify a different
 value of payment method in PaymentMethodUsed.
 For GetOrders, this is also applicable to Half.com.
 
 
 type: string constant in Trading_BuyerPaymentMethodCodeType.h
*/
@property (nonatomic, retain) NSString *paymentMethod;

/**
 
 The status of the order.
 Also applicable to Half.com (for GetOrders).
 
 
 type: string constant in Trading_CompleteStatusCodeType.h
*/
@property (nonatomic, retain) NSString *status;

/**
 
 Indicates whether the item can be paid for through a payment gateway (Payflow) account.
 If IntegratedMerchantCreditCardEnabled is true, then integrated merchant credit card (IMCC) is
 enabled for credit cards because the seller has a payment gateway account.
 Therefore, if IntegratedMerchantCreditCardEnabled is true, and AmEx, Discover, or
 VisaMC is returned for an item, then on checkout, an online credit-card payment
 is processed through a payment gateway account.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *integratedMerchantCreditCardEnabled;



@end
