//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Status of the delivery.
 
 
 @ingroup Trading
*/

/**
 
 Created (default).
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_CREATED;

/**
 
 Dropped off.
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_DROPPED_OFF;

/**
 
 In transit.
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_IN_TRANSIT;

/**
 
 Delivered.
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_DELIVERED;

/**
 
 Returned.
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_RETURNED;

/**
 
 Cancelled.
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_CANCELED;

/**
 
 Label printed.
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_LABEL_PRINTED;

/**
 
 Unconfirmed.
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_UNCONFIRMED;

/**
 
 Unknown.
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_UNKNOWN;

/**
 
 Error.
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_ERROR;

/**
 
 Reserved for future use.
 
*/
extern NSString *const Trading_ShipmentDeliveryStatusCodeType_CUSTOM_CODE;
  
