//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 This code identifies the status of the bid group.
 
 
 @ingroup Trading
*/

/**
 
 (out) Indicates that the bid group is open.
 
*/
extern NSString *const Trading_BidGroupStatusCodeType_OPEN;

/**
 
 (out) Indicates that the bid group is Closed.
 
*/
extern NSString *const Trading_BidGroupStatusCodeType_CLOSED;

/**
 
 Reserved for future use.
 
*/
extern NSString *const Trading_BidGroupStatusCodeType_CUSTOM_CODE;
  
