//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_UserType;
@class Trading_AmountType;

/**
 
 Contains information pertaining to an offer made on an item listing and
 the current bidding or purchase state of the listing.
 
 
 @ingroup Trading
*/
@interface Trading_OfferType : NSObject <EbayNs_Bindable> {

@private
    NSString *action;
    NSString *currency;
    NSString *itemID;
    Trading_AmountType *maxBid;
    NSNumber *quantity;
    NSNumber *secondChanceEnabled;
    NSString *siteCurrency;
    NSDate *timeBid;
    Trading_AmountType *highestBid;
    Trading_AmountType *convertedPrice;
    NSString *transactionID;
    Trading_UserType *user;
    NSNumber *userConsent;
    NSNumber *bidCount;
    NSString *message;
    NSString *bestOfferID;
    Trading_AmountType *myMaxBid;

}


/**
 
 Indicates the type of offer being made on the specified listing.
 If the item is best-offer enabled and the buyer
 makes a best offer (or counter-offer, etc.), then after
 the PlaceOffer call,
 the buyer can get the status of the best offer
 (and of a possible seller-counter-offer, etc.)
 using the GetBestOffers call. See the
 Trading Web Services Guide for information
 about best-offer enabled items and
 about GetBestOffers.
 
 
 type: string constant in Trading_BidActionCodeType.h
*/
@property (nonatomic, retain) NSString *action;

/**
 
 Numeric ID for the currency for the auction. Valid values are
 enumerated in the CurrencyCodeType code list.
 
 
 type: string constant in Trading_CurrencyCodeType.h
*/
@property (nonatomic, retain) NSString *currency;

/**
 
 The unique identifier of an item listed on the eBay site.
 Returned by eBay when the item is created.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *itemID;

/**
 
 Amount of the offer placed. For competitive-bidding listings, the amount
 bid on the item (subject to outbid by other buyers). For fixed-price
 listings, the fixed sale price at which the item is purchased. For
 competitive-bidding listings with an active Buy It Now option, this amount
 will be either the Buy It Now price for purchase or the amount of a bid,
 depending on the offer type (as specified in Action). For PlaceOffer,
 the currencyID attribute is ignored if provided. Regarding Value-Added Tax (VAT):
 Even if VAT applies, you do not need to add VAT to the MaxBid value.
 If VAT applies to the listing, the seller can specify a VAT percent value
 when they list the item.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *maxBid;

/**
 
 Specifies the number of items from the specified listing the user
 tendering the offer intends to purchase, bid on, or make a best offer on.
 For Chinese auctions and
 other listing formats that only allow one item per listing, value may not
 exceed one. For multi-item listings, must be greater than zero and not
 exceeding the number of items offered for sale in the listing.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *quantity;

/**
 
 Indicates the user's preference to accept second chance offers. If true,
 the user is willing to be the recipient of second chance offers.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *secondChanceEnabled;

/**
 
 Unique ID identifying the currency in which the localized offer amounts are
 expressed.
 
 
 type: string constant in Trading_CurrencyCodeType.h
*/
@property (nonatomic, retain) NSString *siteCurrency;

/**
 
 Date and time the offer or bid was placed.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *timeBid;

/**
 
 Amount the highest bidder has bid on the item. Applicable to only
 competitive-bid item listings where there is progressive bidding
 and winning bidders are determined based on the highest bid.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *highestBid;

/**
 
 Localized amount for the item's current price.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *convertedPrice;

/**
 
 The unique identifier of the transaction. The transaction
 is created when a winning bidder commits to purchasing an
 item, even before the bidder has paid.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *transactionID;

/**
 
 Bidder information. See the schema documentation for UserType for details
 on its properties and their meanings.
 
 
 type : class Trading_UserType
*/
@property (nonatomic, retain) Trading_UserType *user;

/**
 
 If true, confirms that the bidder read and agrees to eBay's
 privacy policy. Applies if the subject item is in a category
 that requires user consent. If user consent (that is,
 confirmation that a bidder read and agrees to eBay's privacy
 policy) is required for a category that the subject item is in,
 this value must be true for a bid to occur.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *userConsent;

/**
 
 Total number of offers the user has made on the item.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *bidCount;

/**
 
 A message from the buyer to the seller. Applies if the buyer
 is using PlaceOffer to perform a best-offer-related
 action (best offer, counter-offer, etc.).
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *message;

/**
 
 The ID of a best offer on an item. Must be specified as input to PlaceOffer only if a
 buyer is accepting or declining a seller's counteroffer (and is not required for a
 buyer's offer or counteroffer).
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *bestOfferID;

/**
 
 Maximum bid placed by the user making the call.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *myMaxBid;



@end
