//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Store logo.
 
 
 @ingroup Trading
*/
@interface Trading_StoreLogoType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *logoID;
    NSString *name;
    NSString *url;

}


/**
 
 Store logo ID (use GetStoreOptions to get the list of valid logo IDs).
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *logoID;

/**
 
 Store logo name. Provides a user-friendly name for the logo.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *name;

/**
 
 URL of the logo. Must have a .gif or .jpg extention. Specified when
 you are using a customized logo.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *url;



@end
