//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_MyMessagesFolderSummaryType;

/**
 
 Summary data for a given user's alerts and messages.
 This includes the numbers of new alerts and messages,
 unresolved alerts, flagged messages, and total alerts
 and messages.
 
 
 @ingroup Trading
*/
@interface Trading_MyMessagesSummaryType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *folderSummary;
    NSNumber *newAlertCount;
    NSNumber *newMessageCount;
    NSNumber *unresolvedAlertCount;
    NSNumber *flaggedMessageCount;
    NSNumber *totalAlertCount;
    NSNumber *totalMessageCount;
    NSNumber *newHighPriorityCount;
    NSNumber *totalHighPriorityCount;

}


/**
 
 Folder summary for each folder. Always
 returned for detail level ReturnSummary.
 
 
 entry type : class Trading_MyMessagesFolderSummaryType
*/
@property (nonatomic, retain) NSMutableArray *folderSummary;

/**
 
 The number of new alerts that a given user
 has. Always returned for detail level ReturnSummary.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *newAlertCount;

/**
 
 The number of new messages that a given user has. Always returned for detail level ReturnSummary.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *newMessageCount;

/**
 
 The number of alerts that are not yet
 resolved. Always returned for detail level
 ReturnSummary.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *unresolvedAlertCount;

/**
 
 The number of messages that have been flagged.
 Always returned for detail level ReturnSummary.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *flaggedMessageCount;

/**
 
 The total number of alerts for a given user.
 Always returned for detail level ReturnSummary.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalAlertCount;

/**
 
 The total number of messages for a given user.
 Always returned for detail level ReturnSummary.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalMessageCount;

/**
 
 The total number of new high priority messages that a given user has.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *newHighPriorityCount;

/**
 
 The total number of high priority messages that a given user has.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalHighPriorityCount;


@end
