//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Specifies the type of link in the custom listing header.
 
 
 @ingroup Trading
*/

/**
 
 No type.
 
*/
extern NSString *const Trading_StoreCustomListingHeaderLinkCodeType_NONE;

/**
 
 Link is to an About Me page.
 
*/
extern NSString *const Trading_StoreCustomListingHeaderLinkCodeType_ABOUT_ME_PAGE;

/**
 
 Link is to a custom page.
 
*/
extern NSString *const Trading_StoreCustomListingHeaderLinkCodeType_CUSTOM_PAGE;

/**
 
 Link is to a custom category.
 
*/
extern NSString *const Trading_StoreCustomListingHeaderLinkCodeType_CUSTOM_CATEGORY;

/**
 
    (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_StoreCustomListingHeaderLinkCodeType_CUSTOM_CODE;
  
