//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_CharacteristicsSetType;
@class Trading_ExtendedProductFinderIDType;

/**
 
         Container for data on one listing category.
 
 
 @ingroup Trading
*/
@interface Trading_CategoryType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *bestOfferEnabled;
    NSNumber *autoPayEnabled;
    NSNumber *b2BVATEnabled;
    NSNumber *catalogEnabled;
    NSString *categoryID;
    NSNumber *categoryLevel;
    NSString *categoryName;
    NSMutableArray *categoryParentID;
    NSMutableArray *categoryParentName;
    NSNumber *productSearchPageAvailable;
    NSMutableArray *productFinderIDs;
    NSMutableArray *characteristicsSets;
    NSNumber *expired;
    NSNumber *intlAutosFixedCat;
    NSNumber *leafCategory;
    NSNumber *virtual;
    NSNumber *numOfItems;
    NSNumber *sellerGuaranteeEligible;
    NSNumber *orpa;
    NSNumber *orra;
    NSNumber *lsd;
    NSString *keywords;

}


/**
 
 If true, the category supports best offers.
 If not present, the category does not support best offers.
 Will not be returned if false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *bestOfferEnabled;

/**
 
 If true, indicates that the category supports immediate payment.
 If not present, the category does not support
 immediate payment. Will not be returned if false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *autoPayEnabled;

/**
 
 If true, the category supports business-to-business (B2B) VAT
 listings. Applicable to the eBay Germany (DE), Austria (AT),
 and Switzerland CH) sites only. If not present,
 the category does not support this feature. Will not be returned if false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *b2BVATEnabled;

/**
 
 If true, the category is associated with catalog content
 and the corresponding catalog is identified by the
 characteristic set ID. See CharacteristicsSets.
 As the Pre-filled Item Information feature uses the
 Item Specifics feature, the set of catalog-enabled categories
 is a subset of the categories that are mapped
 to characteristic sets. Not returned if false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *catalogEnabled;

/**
 
 Distinct numeric ID for a category on eBay.
 In GetItem and related calls, see CategoryName for the text name of
 the category. Use GetCategories to look up the category parent ID.<br>
 <br>
 For GetPopularKeywords, -1 represents the root
 category.<br>
 <br>
 For GetItem, Half.com items return the Half.com category ID
 in PrimaryCategory. This ID is not necessarily returned in
 GetCategories.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *categoryID;

/**
 
 The level where the category fits in the site's category hierarchy.
 For example, if this field has a value of 2, then the category is two
 levels below the root category in the site's category hierarchy.
 For the GetSearchResults response, NumOfItems indicates the total
 quantity of matching items in a category. Matching categories at the
 same level (i.e., in sibling categories) are sorted by NumOfItems,
 descending order.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *categoryLevel;

/**
 
 Display name of the category as it would appear on
 the eBay Web site.
 In GetItem, this is a fully qualified category name
 (e.g., Collectibles:Decorative Collectibles:Hummel, Goebel).<br>
 <br>
 In GetItem, always returned for eBay.com listings.
 Not returned in PrimaryCategory for Half.com listings.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *categoryName;

/**
 
 Category ID identifying a category that is an ancestor of
 the category indicated in CategoryID.
 For GetCategories, returns the same value as CategoryID
 if the CategoryLevel is 1.
 For GetSuggestedCategories, multiple CategoryParentID fields
 can be returned in sequence, starting with the root category
 and ending with the category that is the direct parent of
 the category specified in CategoryID.
 Use these parent fields and the CategoryID field to build
 the fully qualified category browse path or "breadcrumbs"
 (e.g., 58058:3516:3517).
 For GetPopularKeywords, -1 represents the root category.
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *categoryParentID;

/**
 
 Display name of the category indicated in CategoryParentID.
 For GetSuggestedCategories, multiple CategoryParentName fields
 can be returned in sequence, starting with the root category
 and ending with the category that
 is the direct parent of the category specified in CategoryName.
 Use these parent fields and the CategoryName field to build the
 fully qualified category browse path or "breadcrumbs"
 (e.g., Computers & Networking > Technology Books > Certification).
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *categoryParentName;

/**
 
 Returned from GetCategory2CS calls. Supports listing with Pre-filled Item Information.
 If the category supports single-attribute search, this field returns a value of
 true. Otherwise this field not returned or returned as false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *productSearchPageAvailable;

/**
 
 The category supports listing with Pre-filled Item Information.
 Specifies the buy-side and/or sell-side product finder IDs associated with this category, if any.
 
 
 entry type : class Trading_ExtendedProductFinderIDType
*/
@property (nonatomic, retain) NSMutableArray *productFinderIDs;

/**
 
 Returned from GetCategory2CS calls.
 A list of one or more characteristics sets mapped to the category. Use this
 information when working with Item Specifics (Attributes) and Pre-filled Item
 Information (Catalogs) functionality. Output only.
 
 
 entry type : class Trading_CharacteristicsSetType
*/
@property (nonatomic, retain) NSMutableArray *characteristicsSets;

/**
 
 If true, indicates a category that has expired and
 to which items may not be listed. Will not be returned if false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *expired;

/**
 
 If true, indicates that the category is a fixed-fee category. Use this
 information to identify categories are not eligible for eBay Stores Inventory
 format listings. You cannot list eBay Store Inventory format listings in
 fixed-fee categories on international sites. Output only. Will not be returned if false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *intlAutosFixedCat;

/**
 
 If true, indicates that the category indicated in CategoryID is a leaf category,
 in which items may be listed (if the category is not also expired or virtual). Will not be returned if false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *leafCategory;

/**
 
 If true, indicates the category indicated in CategoryID is a
 virtual category, to which items may not be listed. Will not be returned if false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *virtual;

/**
 
 The total quantity of matching items in the category.
 In the GetSearchResults response, matching categories at the same level
 (i.e., sibling categories) are sorted by this value. That is, if the request
 specifies that fewer categories or subcategories should be returned,
 the ones with the most matching items are returned first.
 See the Developer's guide for more information.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *numOfItems;

/**
 
 Indicates whether this category is eligible for Motors Seller Guarantee program.
 This tag is emitted for eligible categories only on the eBay Motors site. Will not be returned if false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *sellerGuaranteeEligible;

/**
 
 Indicates whether the category (and its subcategories)
 allows or disallows listing with a reserve price,
 depending on the prevailing site configuration indicated by
 ReservePriceAllowed.
 ORPA (override reserve price allowed) indicates when the category
 is an exception to the site's ReservePriceAllowed policy.<br>
 <br>
 If ORPA is true, the category overrides (toggles or reverses) the
 site's ReservePriceAllowed setting. In other words:<br>
 - If ReservePriceAllowed is true, reserve price is not allowed in this category.<br>
 - If ReservePriceAllowed is false, reserve price is allowed in this category.<br><br>
 If ORPA is not present, there is no override.
 That is, the category's setting is the same as the site's ReservePriceAllowed setting.<br>
 <br> This field will not be returned in the response if false.
 This toggling logic is designed to reduce the size of the GetCategories
 response by only returning ORPA when the category's policy is different
 from the site's policy. (If ORPA is true for a category, you can assume
 its subcategories inherit the same setting unless otherwise specified.)
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *orpa;

/**
 
 Indicates whether the category (and its subcategories) allows
 or disallows reducing a listing's reserve price,
 depending on the prevailing site configuration indicated by ReduceReserveAllowed.
 ORRA (override reduce reserve allowed) indicates when the category is an exception
 to the site's ReduceReserveAllowed policy.<br><br>
 If ORRA is true, the category overrides (toggles or reverses) the
 site's ReduceReserveAllowed setting. In other words:<br>
 - If ReduceReserveAllowed is true, reserve price reduction is not allowed in this category.<br>
 - If ReduceReserveAllowed is false (because it is not present in the response), reserve price reduction is allowed in this category.<br><br>
 If ORRA is not present, there is no override. Will not be returned in the response if false.
 That is, the category's setting is the same as the site's ReduceReserveAllowed setting.<br>
 <br>
 This toggling logic is designed to reduce the size of the GetCategories
 response by only returning ORRA when the category's policy is different
 from the site's policy.  (If ORRA is true for a category, you can assume
 its subcategories inherit the same setting unless otherwise specified.)
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *orra;

/**
 
 Item.LotSize is not permitted when you list in this category.
 If true, indicates that lot sizes are disabled in the specified category. Will not be returned if false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *lsd;

/**
 
 The list of keywords returned by GetPopularKeywords.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *keywords;



@end
