//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_PromotedItemType;

/**
 
 Contains one or more items cross-promoted with
 the display or purchase of a referring item.
 
 
 @ingroup Trading
*/
@interface Trading_CrossPromotionsType : NSObject <EbayNs_Bindable> {

@private
    NSString *itemID;
    NSString *primaryScheme;
    NSString *promotionMethod;
    NSString *sellerID;
    NSNumber *shippingDiscount;
    NSString *storeName;
    NSMutableArray *promotedItem;

}


/**
 
 Unique item ID for the referring item.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *itemID;

/**
 
 The primary cross-promotion rule scheme that
 was applied to return the cross-promoted item.
 
 
 type: string constant in Trading_PromotionSchemeCodeType.h
*/
@property (nonatomic, retain) NSString *primaryScheme;

/**
 
 The type of promotion, CrossSell or UpSell.
 
 
 type: string constant in Trading_PromotionMethodCodeType.h
*/
@property (nonatomic, retain) NSString *promotionMethod;

/**
 
 The eBay user ID of the seller offering the
 cross-promoted item.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *sellerID;

/**
 
 Whether a shipping discount is offered by the seller
 when the cross-promoted item is purchased.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *shippingDiscount;

/**
 
 The store name of the seller offering the cross-promoted item.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *storeName;

/**
 
 Contains one cross-promoted item.
 
 
 entry type : class Trading_PromotedItemType
*/
@property (nonatomic, retain) NSMutableArray *promotedItem;



@end
