//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Used for storing an optional reference ID to the binary attachment
 
 
 @ingroup Trading
*/
@interface Trading_Base64BinaryType : NSObject <EbayNs_Bindable> {

@private
    NSInputStream *value;
    NSString *contentType;

}


/**
 (public property)
 
 type : NSInputStream, wrapper for primitive data
*/
@property (nonatomic, retain) NSInputStream *value;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *contentType;


@end
