//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Trading_AbstractRequestType.h"


@class Trading_VariationKeyType;

/**
 
 Enables a user to remove one or more items from their My eBay watch list.
 
 
 @ingroup Trading
*/
@interface Trading_RemoveFromWatchListRequestType : Trading_AbstractRequestType {

@private
    NSMutableArray *itemID;
    NSNumber *removeAllItems;
    NSMutableArray *variationKey;

}


/**
 
 The ID of the item to be removed from the
 watch list. Either ItemID, RemoveAllItems, or VariationKey must
 be specified, but NOT more than one of these.
 Multiple ItemID fields can be specified in the same request.
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *itemID;

/**
 
 If true, then all the items in the user's
 watch list are removed. Either ItemID, RemoveAllItems, or VariationKey must be specified, but NOT more than one of these.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *removeAllItems;

/**
 
 A variation (or set of variations) that you want to remove
 from the watch list. Either ItemID, RemoveAllItems, or VariationKey must be specified, but NOT more than one of these.
 
 
 entry type : class Trading_VariationKeyType
*/
@property (nonatomic, retain) NSMutableArray *variationKey;


@end
