//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_ItemBestOffersType;

/**
 
 A collection of details about the best offers received for a specific item. Empty if there are no best offers. Includes the buyer and seller messages only if
 the ReturnAll detail level is used.
 
 
 @ingroup Trading
*/
@interface Trading_ItemBestOffersArrayType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *itemBestOffers;

}


/**
 
 A collection of details about the best offers received for a specific item. Empty if
 there are no best offers. Includes the buyer and seller messages only if the ReturnAll
 detail level is used.
 
 
 entry type : class Trading_ItemBestOffersType
*/
@property (nonatomic, retain) NSMutableArray *itemBestOffers;



@end
