//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_OfferType;

/**
 
 Container for a list of offers. May contain zero, one, or multiple
 OfferType objects, each of which represents one offer extended by
 a user on a listing.
 
 
 @ingroup Trading
*/
@interface Trading_OfferArrayType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *offer;

}


/**
 
 Contains the data for one offer. This includes: data for the user making the
 offer, the amount of the offer, the quantity of items being bought from the
 listing, the type of offer being made, and more.
 
 
 entry type : class Trading_OfferType
*/
@property (nonatomic, retain) NSMutableArray *offer;


@end
