//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
  
 Defines the LocalListingDistancesRegular feature. This feature displays all the supported local listing 
 distances for items listed by sellers subscribed to Local Market for Vehicles.
 
 
 @ingroup Trading
*/
@interface Trading_LocalListingDistancesRegularDefinitionType : NSObject <EbayNs_Bindable> {

@private

}




@end
