//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_DiscountProfileType;

/**
 
 Details of an individual discount profile defined by the
 user for flat rate shipping.
 
 
 @ingroup Trading
*/
@interface Trading_FlatShippingDiscountType : NSObject <EbayNs_Bindable> {

@private
    NSString *discountName;
    NSMutableArray *discountProfile;

}


/**
 
 The type of discount or "rule" that is being used by the profile.
 The value corresponding to the selected rule is set in the same-named field
 of FlatShippingDiscount.DiscountProfile. All are "variable" rules, as
 defined in the documentation on shipping discount profiles.
 
 
 type: string constant in Trading_DiscountNameCodeType.h
*/
@property (nonatomic, retain) NSString *discountName;

/**
 
 Details of this particular flat rate shipping discount profile. If
 ModifyActionCode is Modify, all details of the new version of the profile must
 be provided. If ModifyActionCode is Delete, DiscountProfileID is required,
 MappingDiscountProfileID is optional, and all other fields of DiscountProfile
 are ignored. Restrictions of how many profiles you can have for a given
 discount rule are discussed in the documentation on shipping discount
 profiles.
 
 
 entry type : class Trading_DiscountProfileType
*/
@property (nonatomic, retain) NSMutableArray *discountProfile;



@end
