//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>


extern NSString *const Trading_ShipmentStatusCodeType_ACTIVE;

extern NSString *const Trading_ShipmentStatusCodeType_CANCELED;

extern NSString *const Trading_ShipmentStatusCodeType_CUSTOM_CODE;
  
