//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Specifies how the custom listing header will be displayed.
 
 
 @ingroup Trading
*/

/**
 
 No custom listing header is displayed.
 
*/
extern NSString *const Trading_StoreCustomListingHeaderDisplayCodeType_NONE;

/**
 
 The full custom listing header is displayed.
 
*/
extern NSString *const Trading_StoreCustomListingHeaderDisplayCodeType_FULL;

/**
 
 The full custom listing header and the left navigation bar is displayed.
 
*/
extern NSString *const Trading_StoreCustomListingHeaderDisplayCodeType_FULL_AND_LEFT_NAVIGATION_BAR;

/**
 
   (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_StoreCustomListingHeaderDisplayCodeType_CUSTOM_CODE;
  
