//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Indicates whether the category supports the use of payment method checkOut
 for Classified Ad format listings.Added for EbayMotors Pro users.
 
 
 @ingroup Trading
*/
@interface Trading_EBayMotorsProPaymentMethodCheckOutEnabledDefinitionType : NSObject <EbayNs_Bindable> {

@private

}




@end
