//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 A shipping rate scale for shipping through UPS that
 affects the shipping cost calculated for UPS (lower if
 ShippingRateType is DailyPickup). For calculated shipping only.
 
 
 @ingroup Trading
*/

/**
 
 "On-demand" shipping rate scale.
 
*/
extern NSString *const Trading_ShippingRateTypeCodeType_ON_DEMAND;

/**
 
 "Daily pickup" shipping rate scale.
 
*/
extern NSString *const Trading_ShippingRateTypeCodeType_DAILY_PICKUP;

/**
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_ShippingRateTypeCodeType_CUSTOM_CODE;
  
