//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 A container node for a set of durations that apply to a certain listing enhancements.
 
 
 @ingroup Trading
*/
@interface Trading_ListingEnhancementDurationReferenceType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *duration;

}


/**
 
 Specifies a length of time that a listing enhancement can be used for a listing.
 The value Lifetime means the listing enhancment occurs for the lifetime of the listing.
 Instances of durations other than Lifetime can be purchased multiple times
 while the listing is active.
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *duration;



@end
