//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Defines the rules for using Item Specifics to classify
 variation pictures.
 
 
 @ingroup Trading
*/

/**
 
 If the name is used in VariationSpecifics, then it must 
 be used as the Pictures.VariationSpecificName.
 
*/
extern NSString *const Trading_VariationPictureRuleCodeType_REQUIRED;

/**
 
 If the name is used in VariationSpecifics, then it can 
 be used as the Pictures.VariationSpecificName.
 This is the default for variation-enabled categories.
 
*/
extern NSString *const Trading_VariationPictureRuleCodeType_ENABLED;

/**
 
 The name cannot be used as the Pictures.VariationSpecificName.
 
*/
extern NSString *const Trading_VariationPictureRuleCodeType_DISABLED;

/**
 
 Reserved for future use.
 
*/
extern NSString *const Trading_VariationPictureRuleCodeType_CUSTOM_CODE;
  
