//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Indicates whether the seller making the request can list with certain features.
 A seller's eligibility is determined by their feedback rating.
 
 
 @ingroup Trading
*/
@interface Trading_FeatureEligibilityType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *qualifiesForBuyItNow;
    NSNumber *qualifiesForBuyItNowMultiple;
    NSNumber *qualifiedForFixedPriceOneDayDuration;
    NSNumber *qualifiesForVariations;

}


/**
 
 Indicates whether the seller is eligible to list items with the 'BuyItNow' option.
 A value of true means that the seller is eligible; a value of false indicates that
 they are not eligible.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *qualifiesForBuyItNow;

/**
 
 Indicates whether the seller is eligible to specify the 'BuyItNow' option for
 multiple-item listings. A value of true means that the seller is eligible; a value
 of false indicates that they are not eligible.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *qualifiesForBuyItNowMultiple;

/**
 
 Indicates whether the seller is eligible to list a fixed-price item with a one day
 listing duration. A value of true means that the seller is eligible; a value of false
 indicates that they are not eligible.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *qualifiedForFixedPriceOneDayDuration;

/**
 
 Indicates whether or not the seller is eligible to list
 multi-variation items.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *qualifiesForVariations;



@end
