//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Indicates who owns the user's address.
 
 
 @ingroup Trading
*/

/**
 
 PayPal owns the address.
 
*/
extern NSString *const Trading_AddressOwnerCodeType_PAY_PAL;

/**
 
 eBay owns the address.
 
*/
extern NSString *const Trading_AddressOwnerCodeType_E_BAY;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_AddressOwnerCodeType_CUSTOM_CODE;
  
