//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 A list of unique identifiers for orders.
 
 
 @ingroup Trading
*/
@interface Trading_OrderIDArrayType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *orderID;

}


/**
 
 A unique identifier for an order.
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *orderID;


@end
