//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AverageRatingDetailsType;

/**
  
 Container for average detailed seller ratings.
 If a seller has detailed ratings, they are displayed
 in the Feedback Profile of the seller.
 
 
 @ingroup Trading
*/
@interface Trading_AverageRatingSummaryType : NSObject <EbayNs_Bindable> {

@private
    NSString *feedbackSummaryPeriod;
    NSMutableArray *averageRatingDetails;

}


/**
 
 The summary period for which the detail ratings are calculated.
 
 
 type: string constant in Trading_FeedbackSummaryPeriodCodeType.h
*/
@property (nonatomic, retain) NSString *feedbackSummaryPeriod;

/**
 
 Applicable to sites that support the Detailed Seller Ratings feature.
 The AverageRatingDetails container has information about
 average detailed seller ratings.
 When buyers leave an overall Feedback rating (positive, neutral, or negative) for a seller, they also can leave ratings in four areas: item as described, communication, shipping time, and charges for shipping and handling. Users retrieve detailed ratings as averages of the ratings left by buyers. 
 
 
 entry type : class Trading_AverageRatingDetailsType
*/
@property (nonatomic, retain) NSMutableArray *averageRatingDetails;



@end
