//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AmountType;

/**
 
 Various details about a listing. Some of the details are calculated or derived after
 an item is listed. The details in this type include the start and end time and
 the converted (localized) prices. The details in this type also include
 input values applicable to the Best Offer feature.
 Additional details in this type include flags indicating if a seller
 specified fields whose values are not visible to the requesting user.
 
 
 @ingroup Trading
*/
@interface Trading_ListingDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *adult;
    NSNumber *bindingAuction;
    NSNumber *checkoutEnabled;
    Trading_AmountType *convertedBuyItNowPrice;
    Trading_AmountType *convertedStartPrice;
    Trading_AmountType *convertedReservePrice;
    NSNumber *hasReservePrice;
    NSString *relistedItemID;
    NSString *secondChanceOriginalItemID;
    NSDate *startTime;
    NSDate *endTime;
    NSString *viewItemURL;
    NSNumber *hasUnansweredQuestions;
    NSNumber *hasPublicMessages;
    NSNumber *buyItNowAvailable;
    NSString *sellerBusinessType;
    Trading_AmountType *minimumBestOfferPrice;
    NSString *minimumBestOfferMessage;
    NSString *localListingDistance;
    NSString *tcrOriginalItemID;
    NSString *viewItemURLForNaturalSearch;
    NSNumber *payPerLeadEnabled;
    Trading_AmountType *bestOfferAutoAcceptPrice;

}


/**
 
 If true, the item is listed in a Mature category. Users must accept
 the Mature Category agreement on the eBay site to retrieve
 items listed in Mature categories. (Users do not need to sign
 this agreement to be able to list items in Mature Categories.)
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *adult;

/**
 
 Applicable for Real Estate auctions only. If true, buyers and sellers
 are expected to follow through on the sale. If false, bids for the
 Real Estate auction are only expressions of interest.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *bindingAuction;

/**
 
 Indicates whether checkout is enabled for this item. If true, indicates
 that the seller elects to allow the item purchase to go through the
 checkout process, if the buyer chooses to do so.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *checkoutEnabled;

/**
 
 Converted value of the BuyItNowPrice in the currency of
 the site that returned this response.
 For active items, refresh this value every 24 hours to
 pick up the current conversion rates.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *convertedBuyItNowPrice;

/**
 
 Converted value of the StartPrice in the currency of
 the site that returned this response.
 For active items, refresh this value every 24 hours to
 pick up the current conversion rates.<br>
 <br>
 In multi-variation listings, this value matches the lowest-priced
 variation that is still available for sale.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *convertedStartPrice;

/**
 
 Converted value of the ReservePrice in the currency of the
 site that returned this response. Only returned for listings with
 a reserve price when the requesting user is the listing's seller.
 For active items, refresh this value every 24 hours to
 pick up the current conversion rates.
 Not applicable to Fixed Price and Store Inventory listings.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *convertedReservePrice;

/**
 
 If true, the seller specified a value in ReservePrice.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *hasReservePrice;

/**
 
 Indicates the new item ID for a re-listed item. When an item is
 re-listed, the item ID for the new item is added to the
 old listing, so buyers can navigate to
 the new listing. This value only appears when the old listing is
 retrieved. The RelistedItemID of the original item should reflect the last relist.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *relistedItemID;

/**
 
 The item ID for the original listing from which a second chance offer
 is made. This value is only returned when the data for the second chance
 offer listing is retrieved.
 Output only.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *secondChanceOriginalItemID;

/**
 
 The StartTime value returned by non-search calls such as
 GetItem is the time stamp (in GMT) for when
 the item was listed.
 The StartTime value returned by search calls such
 as GetSearchResults and GetCategoryListings may vary
 from the value returned by GetItem.
 The time value is the same value in the following:
 The StartTime value returned by GetSearchResults,
 the StartTime value returned by GetCategoryListings,
 and the time the item became available for search on
 the eBay site.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *startTime;

/**
 
 Time stamp (in GMT) when the listing is scheduled to end
 (calculated based on the values of StartTime and ListingDuration)
 or the actual end time if the item has ended.
 In GetSearchResults, for StoresFixedPrice items which
 are "Good Till Canceled," this value is 5 minutes later than
 the actual end time of the item. The discrepancy is intended
 to facilitate renewal every 30 days of such items' end times.<br>
 <br>
 In GetSearchResults, the same EndTime may be returned for multiple
 results if the results are variations from the same
 multi-variation listing.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *endTime;

/**
 
 The URL of the Web page where a user can view the listing.
 On the US site, this is called the "View Item" page.
 If you enabled affiliate tracking in a search-related call
 (for example, if you used the AffiliateTrackingDetails container
 in an applicable call), ViewItemURL contains
 a string that includes affiliate tracking information
 (see the <a href=
 "https://www.ebaypartnernetwork.com" target="_blank">eBay Partner Network</a>).<br>
 <br>
 In search results (like the GetSearchResults response), this link
 to the View Item page is configured to select the applicable
 variation.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *viewItemURL;

/**
 
       Indicates whether the item has any unanswered questions. Use
 GetMemberMessages to retrieve unanswered questions for the item if this flag
 indicates that there are any.
     
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *hasUnansweredQuestions;

/**
 
       Indicates whether the item has any publicly displayed messages. Use
 GetMemberMessages to retrieve public messages for the item if this flag
 indicates that there are any.
     
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *hasPublicMessages;

/**
 
 Indicates whether Buy It Now is available for the competitive-bid auction listing.
 As a general rule, once a Chinese auction has bids (and the high bid exceeds the
 reserve price, if any), the listing is no longer eligible for Buy It Now.
 <br><br>
 On some sites, the Buy It Now price for a Chinese auction may remain available for
 certain categories even after a bid is placed. See the "Longer Lasting Buy It Now"
 link below for more details and the latest list of eBay US categories that support
 this behavior. The eBay Spain site supports this behavior for all categories.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *buyItNowAvailable;

/**
 
 Type of seller account. This value is not returned for most sites.
 This value is not returned for the German site
 (site ID 77) or eBay Motors site (site ID 100).
 
 
 type: string constant in Trading_SellerBusinessCodeType.h
*/
@property (nonatomic, retain) NSString *sellerBusinessType;

/**
 
 Specifies the minimum acceptable best offer price. If a buyer
 submits a best offer that is below this value, the offer is automatically
 declined by the seller. Applies only to items listed in categories that
 support the Best Offer Auto-Decline feature. Best Offer must be enabled
 for the item, and only the seller who listed the item can see this value.
 To remove this value when revising or relisting an item, use DeletedField.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *minimumBestOfferPrice;

/**
 
 Specifies the message sent from the seller to the buyer when a
 submitted best offer is automatically declined by the seller. A best offer
 is automatically declined if it does not meet the minimum acceptable best
 offer price specified by the seller with MinimumBestOfferPrice. Applies only
 to items listed in categories that support the Best Offer Auto-Decline
 feature. Best Offer must be enabled for the item.
 To remove this value when revising or relisting an item, use DeletedField.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *minimumBestOfferMessage;

/**
 
 Specifies a distance (in miles) used as the radius of the area about the
 supplied postal code that constitutes the local market. Use
 GetCategoryFeatures to determine the local listing distances supported by
 a given site, category, and Local Market subscription level.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *localListingDistance;

/**
 
 Indicates the item ID of the original item listing from which a
 Transaction Confirmation Request (TCR) was created. This value is only
 returned when the data for a TCR is retrieved.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *tcrOriginalItemID;

/**
 
 This URL takes you to the same View Item page as ViewItemURL,
 but this URL is optimized to support natural search.
 That is, this URL is designed to make items on eBay easier to find via
 popular Internet search engines. The URL includes the item title along with other optimizations. To
 note, "?" (question mark) optimizes to "_W0QQ", "&" (ampersand) optimizes
 to "QQ", and "=" (equals sign) optimizes to "Z".
 <br><br>
 If you are an eBAy affiliate, use this URL to promote your affiliate
 information.
 <br><br>
 <span class="tablenote"><b>Note:</b>
 This URL may include additional query parameters that don't appear in ViewItemURL
 and vice versa. You should not modify the query syntax.  For example, eBay won't
 recognize the URL if you change QQ to ?.
 </span>
 <br><br>
 In search results (like the GetSearchResults response), if the
 result is a variation from a multi-variation listing, this link
 to the View Item page is configured to select the applicable
 variation.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *viewItemURLForNaturalSearch;

/**
 
 If true as an input or output field, the item is pay-per-lead-enabled.
 This field applies to the pay-per-lead feature, which is
 planned for availability on the US site in upcoming months.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *payPerLeadEnabled;

/**
 
 The price at which best offers are automatically accepted. Similar in use to
 MinimumBestOfferPrice. If a buyer submits a best offer that is above this value, the
 offer is automatically accepted by the seller. Applies only to items listed in
 categories that support the BestOfferAutoAcceptPrice feature. Best Offer must be
 enabled for the item, and only the seller who listed the item will see
 BestOfferAutoAcceptPrice in a call response. On the US eBay Motors site (site ID
 100), you cannot use the API to add a minimum best offer price. For a ReviseItem call
 with site ID 100, prior use of a minimum best offer price on eBay.com is ignored.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *bestOfferAutoAcceptPrice;



@end
