//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AddressType;

/**
 
 Contains information about a user as a buyer.
 
 
 @ingroup Trading
*/
@interface Trading_BuyerType : NSObject <EbayNs_Bindable> {

@private
    Trading_AddressType *shippingAddress;

}


/**
 
 Contains the address of the buyer in the transaction, to which the seller
 would ship the item(s). See AddressType for its child elements. GetAllBidders
 is returning only Country and PostalCode currently.
 Output only.
 
 
 type : class Trading_AddressType
*/
@property (nonatomic, retain) Trading_AddressType *shippingAddress;



@end
