//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AmountType;

/**
 
 Container for BestOffer properties associated with the item.
 
 
 @ingroup Trading
*/
@interface Trading_BestOfferDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *bestOfferCount;
    NSNumber *bestOfferEnabled;
    Trading_AmountType *bestOffer;
    NSString *bestOfferStatus;
    NSString *bestOfferType;

}


/**
 
 The number of best offers made for this item, if any. In other words, if there are
 no offers made, this container will not appear in the response.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *bestOfferCount;

/**
 
 Whether best offer is enabled for this item.
 A seller of a fixed price format item (in a category for which Best Offer is also enabled) can
 opt that item into the Best Offer feature. This feature enables a buyer to
 make a lower priced binding offer on that item.
 If a listing has no active best offers, you can change this value (true to false, and vice versa).
 If a listing does have active best offers, you cannot change the value to false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *bestOfferEnabled;

/**
 
 (GetMyeBayBuying only) Indicates the latest BestOffer the user has provided for the item.
 If there are no offers made, this field will not appear in the response.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *bestOffer;

/**
 
 (GetMyeBayBuying only) Indicates the status of the latest BestOffer the buyer has provided for the item.
 If there are no offers made, this field will not appear in the response.
 
 
 type: string constant in Trading_BestOfferStatusCodeType.h
*/
@property (nonatomic, retain) NSString *bestOfferStatus;

/**
 
 Indicates the best offer type of the latest BestOffer the user has provided for the item.
 If there are no offers made, this field will not appear in the response.
 
 
 type: string constant in Trading_BestOfferTypeCodeType.h
*/
@property (nonatomic, retain) NSString *bestOfferType;



@end
