//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 At least one container is required (minOccurs="1") if Pictures container is present in the request.
 
 
 @ingroup Trading
*/
@interface Trading_VariationSpecificPictureSetType : NSObject <EbayNs_Bindable> {

@private
    NSString *variationSpecificValue;
    NSMutableArray *pictureURL;
    NSString *galleryURL;

}


/**
 
 A value that is associated with VariationSpecificName. For example, 
 suppose this set of pictures is showing blue shirts, and some of
 the variations include Color=Blue in their variation specifics. 
 If VariationSpecificName is "Color", then VariationSpecificValue would be "Blue".
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *variationSpecificValue;

/**
 
 The URL of a picture that is associated with VariationSpecificValue.
 Images can be hosted by eBay Picture Services (EPS) or they can be 
 self-hosted, but you can't mix the two. (That is, pictures
 in PictureDetails and VariationSpecificPictureSet need to either all
 be hosted by EPS, or all self-hosted.)
 If specified, this cannot have an empty/null value.
 To specify multiple pictures, send each URL in a separate, adjacent 
 PictureURL field.<br>
 <br>
 The first PictureURL is also used as the gallery picture for 
 applicable variations. 
 For example, if the picture set contains pictures of red shirts
 (i.e., VariationSpecificName=Color and VariationSpecificValue=Red), 
 the first picture is used as the gallery picture for
 all the red shirt variations.<br>
 <br>
 You can use Item.PictureDetails to specify additional pictures. 
 For example, the item-level pictures could include a model wearing a 
 black shirt, as a typical example of the shirt style.
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *pictureURL;

/**
 
 URL for the variation's Gallery thumbnail, which eBay uses when
 the variation is shown in My eBay.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *galleryURL;



@end
