//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Defines the multi-variation listing feature. If the field is present, 
 the  corresponding feature applies to the site. The field is returned as 
 an empty element (e.g., a boolean value is not returned).<br>
 <br>
 Multi-variation listings contain items that are logically the same 
 product, but that vary in their manufacturing details or packaging. 
 For example, a particular brand and style of shirt could be 
 available in different sizes and colors, such as "large blue" and 
 "medium black" variations.
 
 
 @ingroup Trading
*/
@interface Trading_VariationsEnabledDefinitionType : NSObject <EbayNs_Bindable> {

@private

}




@end
