//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Identifies the scheme used for a cross-promotion rule.
 The scheme defines referring and promoted items and categories.
 To define a rule scheme, you must be the owner of an eBay Store.
 
 
 @ingroup Trading
*/

/**
 
 The seller specifies individual items in the store that are
 promoted when a buyer views, bids on, or purchases a store item.
 
*/
extern NSString *const Trading_PromotionSchemeCodeType_ITEM_TO_ITEM;

/**
 
 The seller specifies a store category from which items are promoted
 when a buyer views, bids on, or purchases an individual item in the store.
 
*/
extern NSString *const Trading_PromotionSchemeCodeType_ITEM_TO_STORE_CAT;

/**
 
 The seller specifies referring and promoted categories, both from
 the store. When a buyer views or acts on any item from that category, items
 from the promoted category are also displayed.
 
*/
extern NSString *const Trading_PromotionSchemeCodeType_STORE_TO_STORE_CAT;

/**
 
 The seller specifies a referring item and defines promoted items
 selected from a store category, eBay category, or keywords.
 
*/
extern NSString *const Trading_PromotionSchemeCodeType_ITEM_TO_DEFAULT_RULE;

/**
 
 The seller specifies a store category or eBay category, with
 optional keywords, for referring items and one for promoted items. When a
 referring item is selected from the category and keywords, items from the
 promoted category and keywords are also displayed.
 
*/
extern NSString *const Trading_PromotionSchemeCodeType_DEFAULT_RULE;

/**
 
 This scheme is returned as a backfill scheme used to promote items.
 
*/
extern NSString *const Trading_PromotionSchemeCodeType_CATEGORY_PROXIMITY;

/**
 
 This scheme is returned as related category scheme used to promote
 items.
 
*/
extern NSString *const Trading_PromotionSchemeCodeType_RELATED_CATEGORY_RULE;

/**
 
 This scheme is returned as a backfill scheme used to promote items.
 
*/
extern NSString *const Trading_PromotionSchemeCodeType_DEFAULT_UP_SELL_LOGIC;

/**
 
 This scheme is returned as a backfill scheme used to promote items.
 
*/
extern NSString *const Trading_PromotionSchemeCodeType_DEFAULT_CROSS_SELL_LOGIC;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_PromotionSchemeCodeType_CUSTOM_CODE;
  
