//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_ListingDurationDefinitionType;

/**
 
 A container node for sets of durations, each set describing the durations allowed for
 one listing type.
 
 
 @ingroup Trading
*/
@interface Trading_ListingDurationDefinitionsType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *listingDuration;
    NSNumber *version;

}


/**
 
 Contains the duration periods that apply to a certain listing type.
 
 
 entry type : class Trading_ListingDurationDefinitionType
*/
@property (nonatomic, retain) NSMutableArray *listingDuration;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *version;


@end
