//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Contains an array of eBay UserID entries. 
 
 
 @ingroup Trading
*/
@interface Trading_UserIDArrayType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *userID;

}


/**
 
 Unique eBay user ID for the user. 
 Applies to eBay Motors Pro applications only. 
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *userID;



@end
