//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 The imposition (tax type).
 
 
 @ingroup Trading
*/

/**
 
 Sales tax.
 
*/
extern NSString *const Trading_TaxTypeCodeType_SALES_TAX;

/**
 
 Waste recycling fee.
  
*/
extern NSString *const Trading_TaxTypeCodeType_WASTE_RECYCLING_FEE;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_TaxTypeCodeType_CUSTOM_CODE;
  
