//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Specifies whether a listing feature is available for the site specified in the request.
 
 
 @ingroup Trading
*/

/**
 
 The listing feature is enabled for the site.
 
*/
extern NSString *const Trading_HomePageFeaturedCodeType_ENABLED;

/**
 
 The listing feature is disabled for the site.
 
*/
extern NSString *const Trading_HomePageFeaturedCodeType_DISABLED;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_HomePageFeaturedCodeType_CUSTOM_CODE;
  
