//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Details about type of Carrier used to ship an item.
 
 
 @ingroup Trading
*/
@interface Trading_ShippingCarrierDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *shippingCarrierID;
    NSString *description;
    NSString *shippingCarrier;
    NSString *detailVersion;
    NSDate *updateTime;

}


/**
 
 Numeric identifier.
 Some applications use this ID
 to look up shipping Carriers more efficiently.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *shippingCarrierID;

/**
 
 Full name of the shipping Carrier for display purposes.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *description;

/**
 
 Value used for the shipping Carrier.
 
 
 type: string constant in Trading_ShippingCarrierCodeType.h
*/
@property (nonatomic, retain) NSString *shippingCarrier;

/**
 
 Returns the latest version number for this field. The version can be
 used to determine if and when to refresh cached client data.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *detailVersion;

/**
 
 Gives the time in GMT that the feature flags for the details were last
 updated. This timestamp can be used to determine if and when to refresh
 cached client data.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *updateTime;



@end
