//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 [Selling] The minimum feedback score used to determine whether a buyer should be blocked from bidding.
 
 @ingroup Trading
*/
@interface Trading_MinimumFeedbackScoreDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *feedbackScore;

}


/**
 [Selling] The values supported for the minimum feedback score restriction.
 
 entry type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSMutableArray *feedbackScore;



@end
