//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 PayPal address status.
 
 
 @ingroup Trading
*/

extern NSString *const Trading_AddressStatusCodeType_NONE;

extern NSString *const Trading_AddressStatusCodeType_CONFIRMED;

extern NSString *const Trading_AddressStatusCodeType_UNCONFIRMED;

/**
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_AddressStatusCodeType_CUSTOM_CODE;
  
