//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 (public class)
 
 @ingroup Trading
*/
@interface Trading_WarrantyTypeDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSString *warrantyTypeOption;
    NSString *description;

}


/**
 
 The source or type of the warranty.
 This value can be passed in the AddItem family of calls.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *warrantyTypeOption;

/**
 
 Display string that applications can use to present WarrantyTypeOption in
 a more user-friendly format (such as in a drop-down list).
 Not applicable as input to the AddItem family of calls. (Use WarrantyTypeOption instead.)
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *description;



@end
