//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Trading_AbstractResponseType.h"


@class Trading_SuggestedCategoryArrayType;

/**
 
 Returns a list of categories with the highest number
 of listings whose titles or descriptions contain the keywords
 specified in a GetSuggestedCategoriesRequest.
     
 
 @ingroup Trading
*/
@interface Trading_GetSuggestedCategoriesResponseType : Trading_AbstractResponseType {

@private
    Trading_SuggestedCategoryArrayType *suggestedCategoryArray;
    NSNumber *categoryCount;

}


/**
 
 Contains the categories that contain listings
 that match the query string in the request. The array
 can have up to 10 categories. Not returned if no categories match
 the query in the request.
 
 
 type : class Trading_SuggestedCategoryArrayType
*/
@property (nonatomic, retain) Trading_SuggestedCategoryArrayType *suggestedCategoryArray;

/**
 
 Indicates the number of categories in the array.
     
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *categoryCount;


@end
