//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>


/**
 
 (in) Specifies that you want to replace the description text of an item.
 
*/
extern NSString *const Trading_DescriptionReviseModeCodeType_REPLACE;

/**
 
 (in) Specifies that you want to prepend text to the description text of an item.
 
*/
extern NSString *const Trading_DescriptionReviseModeCodeType_PREPEND;

/**
 
 (in) Specifies that you want to append text to the description text of an item.
 
*/
extern NSString *const Trading_DescriptionReviseModeCodeType_APPEND;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_DescriptionReviseModeCodeType_CUSTOM_CODE;
  
