//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_RecommendationValidationRulesType;

/**
 
 Defines details about recommended values for custom Item Specifics.
 
 
 @ingroup Trading
*/
@interface Trading_ValueRecommendationType : NSObject <EbayNs_Bindable> {

@private
    NSString *value;
    Trading_RecommendationValidationRulesType *validationRules;

}


/**
 
 A recommended value for the Item Specific. Only returned when 
 a recommended value is available.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *value;

/**
 
 Constraints that eBay places on this Item Specific value.<br>
 <br>
 Only returned when you configure your request to include 
 relationships and/or confidence, and a recommended value 
 is available. 
 (Not returned when ExcludeRelationships is true and 
 IncludeConfidence is false.)
 
 
 type : class Trading_RecommendationValidationRulesType
*/
@property (nonatomic, retain) Trading_RecommendationValidationRulesType *validationRules;



@end
