//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Trading_AbstractRequestType.h"



/**
 
 Retrieves a map of old category IDs and corresponding active
 category IDs defined for the site to which the request is sent.
 
 
 @ingroup Trading
*/
@interface Trading_GetCategoryMappingsRequestType : Trading_AbstractRequestType {

@private
    NSString *categoryVersion;

}


/**
 
  A version of the category mapping for the site. Filters
  out data from the call to return only the category
  mappings for which the data has changed since the
  specified version. If not specified, all category
  mappings are returned. Typically, an application passes
  the version value of the last set of category mappings
  that the application stored locally. The latest version
  value is not necessarily greater than the previous value
  that was returned. Therefore, when comparing versions,
  only compare whether the value has changed.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *categoryVersion;


@end
