//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Defines the feature that specifies whether a handling time (dispatch time)
 could be enabled on the site.
 
 
 @ingroup Trading
*/
@interface Trading_HandlingTimeEnabledDefinitionType : NSObject <EbayNs_Bindable> {

@private

}




@end
