//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AmountType;

/**
 
         Shipping costs and options related to an international shipping service. When used
 as input, if one is provided, at least one domestic ShippingService must be
 provided.
 
 
 @ingroup Trading
*/
@interface Trading_InternationalShippingServiceOptionsType : NSObject <EbayNs_Bindable> {

@private
    NSString *shippingService;
    Trading_AmountType *shippingServiceCost;
    Trading_AmountType *shippingServiceAdditionalCost;
    NSNumber *shippingServicePriority;
    NSMutableArray *shipToLocation;
    Trading_AmountType *shippingInsuranceCost;

}


/**
 
 An international shipping service offered for shipping the item.
 For a list of valid values that you can cache for future
 use, call GeteBayDetails with DetailName set to ShippingServiceDetails.
 (NOTE: Not all shipping services returned in GeteBayDetails can be used in new
 listings. Be sure to examine the rules provided in ShippingServiceDetails to
 determine which services can be used in the AddItem family of calls.)
 <br><br>
 For flat and calculated shipping.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *shippingService;

/**
 
 The meaning of this element depends on the call and on whether flat
 or calculated shipping has been selected. (For example, it could be the cost
 to ship a single item, the cost to ship all items, or the cost to ship just
 the first of many items, with ShippingServiceAdditionalCost accounting for the
 rest.) When returned by GetItemShipping, it includes the packaging and
 handling cost. For flat and calculated shipping.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *shippingServiceCost;

/**
 
 The cost of shipping each additional item beyond the first item. For input,
 this is required if the listing is for multiple items. For single-item
 listings, it should be zero (or is defaulted to zero if not provided).
 For flat shipping only.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *shippingServiceAdditionalCost;

/**
 
 Seller-preferred presentation order relative to other
 service options. Valid values are: 1, 2 and 3 (first, second
 and third choices). For flat and calculated shipping.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *shippingServicePriority;

/**
 
 An international location or region to where the item seller will ship the item.
 Use GeteBayDetails to determine which locations are valid per site. These values
 are string equivalents of values found in ShippingRegionCodeType and
 CountryCodeType. For the AddItem family of calls, this field is required if any
 international shipping service is specified.
 
 
 entry type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSMutableArray *shipToLocation;

/**
 
 The insurance cost associated with shipping a single item with this shipping
 service. Exception: for GetItemShipping, this is proportional to QuantitySold. If
 the item has not yet been sold, insurance information cannot be calculated and the
 value is 0.00. For calculated shipping only.
 <br><br>
 Valid only on the following sites: AU, FR, and IT
 <br>
 Also applicable to Half.com (for GetOrders).
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *shippingInsuranceCost;



@end
