//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Font selection for Store configuration.
 
 
 @ingroup Trading
*/

/**
 
 Arial font.
 
*/
extern NSString *const Trading_StoreFontFaceCodeType_ARIAL;

/**
 
 Courier font.
 
*/
extern NSString *const Trading_StoreFontFaceCodeType_COURIER;

/**
 
 Times New Roman font.
 
*/
extern NSString *const Trading_StoreFontFaceCodeType_TIMES;

/**
 
 Verdana font.
 
*/
extern NSString *const Trading_StoreFontFaceCodeType_VERDANA;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_StoreFontFaceCodeType_CUSTOM_CODE;
  
