//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 A means for identifying a person's role in doing business on eBay.
 
 
 @ingroup Trading
*/

/**
 
 Acting as buyer.
 
*/
extern NSString *const Trading_TradingRoleCodeType_BUYER;

/**
 
 Acting as seller. For GetOrders, you can use this value to limit orders
 to those where the calling user is the seller.
 
*/
extern NSString *const Trading_TradingRoleCodeType_SELLER;

/**
 
 Reserved for future use.
 
*/
extern NSString *const Trading_TradingRoleCodeType_CUSTOM_CODE;
  
