//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Used to indicate whether custom Item Specifics are enabled for a category.
 
 
 @ingroup Trading
*/

/**
 
 The custom Item Specifics feature is disabled for the category.
 
*/
extern NSString *const Trading_ItemSpecificsEnabledCodeType_DISABLED;

/**
 
 The custom Item Specifics feature is enabled for the category.
 
*/
extern NSString *const Trading_ItemSpecificsEnabledCodeType_ENABLED;

/**
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_ItemSpecificsEnabledCodeType_CUSTOM_CODE;
  
