//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Trading_AbstractResponseType.h"



/**
 
 (out) Returned after a call to SetNotificationPreferences to indicate that the call succeeded.
 
 
 @ingroup Trading
*/
@interface Trading_SetNotificationPreferencesResponseType : Trading_AbstractResponseType {

@private

}



@end
