//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Trading_AbstractRequestType.h"


@class Trading_PaginationType;

/**
 
 Retrieves best offers.
 
 
 @ingroup Trading
*/
@interface Trading_GetBestOffersRequestType : Trading_AbstractRequestType {

@private
    NSString *itemID;
    NSString *bestOfferID;
    NSString *bestOfferStatus;
    Trading_PaginationType *pagination;

}


/**
 
 The ID of the listing for which Best Offer information is to be returned.
 See the description of GetBestOffers
 for details related to who makes the request and how
 ItemID and BestOfferID can be omitted.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *itemID;

/**
 
 The ID of the best offer for which information is to be returned.
 See the description of GetBestOffers
 for details related to who makes the request and how
 ItemID and BestOfferID can be omitted.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *bestOfferID;

/**
 
 A filter that specifies which Best Offers to return for an item (such as countered,
 expired, or accepted).
 
 
 type: string constant in Trading_BestOfferStatusCodeType.h
*/
@property (nonatomic, retain) NSString *bestOfferStatus;

/**
 
 Specifies how to create virtual pages in the returned list (such as total
 number of entries and total number of pages to return).
 
 
 type : class Trading_PaginationType
*/
@property (nonatomic, retain) Trading_PaginationType *pagination;


@end
