//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Container for MaximumUnpaidItemStrikes buyer requirement in item listings.
 A similar tag, BuyerRequirements.MaximumUnpaidItemStrikes has been deprecated.
 
 
 @ingroup Trading
*/
@interface Trading_MaximumUnpaidItemStrikesInfoType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *count;
    NSString *period;

}


/**
 
 Maximum allowed unpaid item strikes against the buyer.
 If the limit is reached, the buyer can not bid on this item.
 Used with Period.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *count;

/**
 
 If a buyer fails to pay for an item, they incur
 an unpaid item strike on their account. The Period and Count elements
 allow a seller to specify that only buyers with a specified number of
 item strikes (or less) within a given period of time can bid on their
 item. If a buyer has more strikes than specified within these limits,
 the buyer can not bid on this item.
 The Period is the past number of days (last 60 days, last 180 days, etc.)
 within which the unpaid item buyer strikes are calculated.
 Used with Count.
 
 
 type: string constant in Trading_PeriodCodeType.h
*/
@property (nonatomic, retain) NSString *period;



@end
