//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Defines the DutchBINEnabled feature. If the field is present, the Buy It Now is
 enabled in this category for Ducth (multi-item) auctions. The field is returned as an
 empty element (i.e., a boolean value is not returned).
 <br><br>
 <span class="tablenote"><strong>Note:</strong>
 As of version 619, Dutch-style (multi-item) competitive-bid auctions are deprecated.
 eBay throws an error if you submit a Dutch item listing with AddItem
 or VerifyAddItem. If you use RelistItem to update a Dutch auction listing,
 eBay generates a warning and resets the Quantity value to 1.
 </span>
 <br>
 
 
 @ingroup Trading
*/
@interface Trading_DutchBINEnabledDefinitionType : NSObject <EbayNs_Bindable> {

@private

}




@end
