//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Trading_AbstractRequestType.h"


@class Trading_BidAssistantListType;
@class Trading_ItemListCustomizationType;
@class Trading_MyeBaySelectionType;

/**
 
 Returns items from the Buying section of the user's My eBay
 account, including items that the user is watching, bidding on, has
 won, has not won, and has made best offers on.
 
 
 @ingroup Trading
*/
@interface Trading_GetMyeBayBuyingRequestType : Trading_AbstractRequestType {

@private
    Trading_ItemListCustomizationType *watchList;
    Trading_ItemListCustomizationType *bidList;
    Trading_ItemListCustomizationType *bestOfferList;
    Trading_ItemListCustomizationType *wonList;
    Trading_ItemListCustomizationType *lostList;
    Trading_MyeBaySelectionType *favoriteSearches;
    Trading_MyeBaySelectionType *favoriteSellers;
    Trading_MyeBaySelectionType *secondChanceOffer;
    Trading_BidAssistantListType *bidAssistantList;
    Trading_ItemListCustomizationType *deletedFromWonList;
    Trading_ItemListCustomizationType *deletedFromLostList;
    Trading_ItemListCustomizationType *buyingSummary;
    Trading_MyeBaySelectionType *userDefinedLists;

}


/**
 
 Returns the list of items being watched by the user.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_ItemListCustomizationType
*/
@property (nonatomic, retain) Trading_ItemListCustomizationType *watchList;

/**
 
 Returns the list of items on which the user has bid.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_ItemListCustomizationType
*/
@property (nonatomic, retain) Trading_ItemListCustomizationType *bidList;

/**
 
 Returns the list of items on which the user has placed best offers.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_ItemListCustomizationType
*/
@property (nonatomic, retain) Trading_ItemListCustomizationType *bestOfferList;

/**
 
 Returns the list of items on which the use has bid.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_ItemListCustomizationType
*/
@property (nonatomic, retain) Trading_ItemListCustomizationType *wonList;

/**
 
 Returns the list of items on which the user has bid on and lost.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_ItemListCustomizationType
*/
@property (nonatomic, retain) Trading_ItemListCustomizationType *lostList;

/**
 
 Returns the list of searches that the user has saved in My eBay. Returned
 only if the user has saved searches.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_MyeBaySelectionType
*/
@property (nonatomic, retain) Trading_MyeBaySelectionType *favoriteSearches;

/**
 
 Returns the list of favorite sellers that the user has saved in My eBay.
 Returned only if the user has saved a list of favorite sellers.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_MyeBaySelectionType
*/
@property (nonatomic, retain) Trading_MyeBaySelectionType *favoriteSellers;

/**
 
 Returns the list of second chance offers made by the user. Returned only
 if the user has made second chance offers.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_MyeBaySelectionType
*/
@property (nonatomic, retain) Trading_MyeBaySelectionType *secondChanceOffer;

/**
 
 Indicates whether or not the Bid Assistant feature is being used.
 
 
 type : class Trading_BidAssistantListType
*/
@property (nonatomic, retain) Trading_BidAssistantListType *bidAssistantList;

/**
 
 Returns the list of items the user has won, and subsequently deleted from
 their My eBay page.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_ItemListCustomizationType
*/
@property (nonatomic, retain) Trading_ItemListCustomizationType *deletedFromWonList;

/**
 
 Returns the list of items (auctions) the user did not win and were
 subsequently deleted from their My eBay page.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_ItemListCustomizationType
*/
@property (nonatomic, retain) Trading_ItemListCustomizationType *deletedFromLostList;

/**
 
 Returns a summary of the user's buying activity.
 <br><br>
 With a request version of 605 or higher, the buying summary container is
 not included in the response by default. Add a BuyingSummary element in
 the request with an Include field set to true to receive a BuyingSummary
 container in your response.
 <br><br>
 With a request version lower than 605, the BuyingSummary is always
 returned by default. Add a BuyingSummary element with an Include field
 set to false to exclude the BuyingSummary from your response.
 
 
 type : class Trading_ItemListCustomizationType
*/
@property (nonatomic, retain) Trading_ItemListCustomizationType *buyingSummary;

/**
 
 Returns the user defined lists, which are lists created by the user in the eBay
 UI and filled with items, or sellers, or searches using the 
 "Add to List" feature.
 <br><br>
 Set Include to true to return the default response set.
 
 
 type : class Trading_MyeBaySelectionType
*/
@property (nonatomic, retain) Trading_MyeBaySelectionType *userDefinedLists;


@end
