//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 ProStores listing level preferences.
 
 
 @ingroup Trading
*/
@interface Trading_ListingCheckoutRedirectPreferenceType : NSObject <EbayNs_Bindable> {

@private
    NSString *proStoresStoreName;
    NSString *sellerThirdPartyUsername;

}


/**
 
 The name of the store, if ThirdPartyCheckout is true.
 To remove this value when revising or relisting an item, use DeletedField.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *proStoresStoreName;

/**
 
 The user name of the associated store, if ThirdPartyCheckout is true.
 To remove this value when revising or relisting an item, use DeletedField.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *sellerThirdPartyUsername;



@end
