//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Trading_AbstractRequestType.h"



/**
 
 Retrieves mappings between categories and characteristic sets
 that are available for an eBay site.
 
 
 @ingroup Trading
*/
@interface Trading_GetCategory2CSRequestType : Trading_AbstractRequestType {

@private
    NSString *categoryID;
    NSString *attributeSystemVersion;

}


/**
 
 ID of a category for which to retrieve mappings.
 If not specified, the call
 retrieves a map for all categories.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *categoryID;

/**
 
 A version of the mappings for the site.
 Typically, an application passes the version value that was returned the last
 time the application executed this call.
 Filter that causes the call to return only the categories
 for which the mappings have changed since the specified version.
 If not specified, all category-to-characteristics set mappings are returned.
 This value changes each time changes are made to the mappings.
 The current version value is not necessarily greater than the previous
 value. Therefore, when comparing versions, only compare whether the
 value has changed.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *attributeSystemVersion;


@end
