//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 The status of a particular entry.
 
 
 @ingroup Trading
*/

/**
 
 The entry is enabled.
 
*/
extern NSString *const Trading_EnableCodeType_ENABLE;

/**
 
 The entry is disabled.
 
*/
extern NSString *const Trading_EnableCodeType_DISABLE;

/**
 
 Reserved for future use.
 
*/
extern NSString *const Trading_EnableCodeType_CUSTOM_CODE;
  
