//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Details the shipping carrier and shipment tracking number associated with a
 package shipment.
 
 
 @ingroup Trading
*/
@interface Trading_ShipmentTrackingDetailsType : NSObject <EbayNs_Bindable> {

@private
    NSString *shippingCarrierUsed;
    NSString *shipmentTrackingNumber;

}


/**
 
 Name of the shipping carrier used to ship the item.
 Returned only if set.
 Returned for Half.com as well.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *shippingCarrierUsed;

/**
 
 The tracking number assigned by the shipping carrier to the item shipment. The
 format of the tracking number must be consistent with the format used by the
 specified shipping carrier (ShippingCarrierUsed).
 Returned only if set.
 Returned for Half.com as well.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *shipmentTrackingNumber;



@end
