//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_LookupAttributeType;

/**
 
 Only valid for items catalog-enabled categories.
 
 
 @ingroup Trading
*/
@interface Trading_LookupAttributeArrayType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *lookupAttribute;

}


/**
 
 The condition of the item. When catalog-enabled categories start 
 supporting the newer ConditionID field in production, use ConditionID instead of LookupAttribute.
 
 
 entry type : class Trading_LookupAttributeType
*/
@property (nonatomic, retain) NSMutableArray *lookupAttribute;


@end
