//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Container of token and image URL and Audio URL.
 
 
 @ingroup Trading
*/
@interface Trading_BotBlockResponseType : NSObject <EbayNs_Bindable> {

@private
    NSString *botBlockToken;
    NSString *botBlockUrl;
    NSString *botBlockAudioUrl;

}


/**
 
 An encrypted token generated by eBay when the botblock
 mechanism is triggered. This token is mapped to BotBlockUrl 
 and BotBlockAudioUrl.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *botBlockToken;

/**
 
 The URL of the image that your application should display to
 the user for a botblock challenge.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *botBlockUrl;

/**
 
 The URL of the audio-clip that your application should provide for sight-impaired users.
 The BotBlockAudioUrl audio-clip corresponds to the BotBlockUrl image.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *botBlockAudioUrl;



@end
