//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 PromotionItemSelectionCodeType - Type declaration to be used by
 other schema. Indicates how the cross-promoted item was selected for
 association with the referring item. If the seller defined an
 item-to-item cross-promotion rule and the item was selected because
 of that rule, then "Manual" is returned. If the seller defined some
 other rule and the item was selected because of that rule (or the
 seller defined no rules that could be applied), then "Automatic" is
 returned.
 
 
 @ingroup Trading
*/

/**
 
 (out) Manual selection.
 
*/
extern NSString *const Trading_PromotionItemSelectionCodeType_MANUAL;

/**
 
 (out) Automatic selection.
 
*/
extern NSString *const Trading_PromotionItemSelectionCodeType_AUTOMATIC;

/**
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_PromotionItemSelectionCodeType_CUSTOM_CODE;
  
