//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
  Characteristics of the My eBay Favorite Seller.
 
 
 @ingroup Trading
*/
@interface Trading_MyeBayFavoriteSellerType : NSObject <EbayNs_Bindable> {

@private
    NSString *userID;
    NSString *storeName;

}


/**
 
 The favorite seller's eBay user ID.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *userID;

/**
 
 The name of the store owned by the favorite seller, if applicable.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *storeName;



@end
