//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AmountType;

/**
 
 If a seller has reduced the price of a listed item with the Promotional Price Display
 feature, this type contains the original price of the discounted item and other
 information.
 
 
 @ingroup Trading
*/
@interface Trading_PromotionalSaleDetailsType : NSObject <EbayNs_Bindable> {

@private
    Trading_AmountType *originalPrice;
    NSDate *startTime;
    NSDate *endTime;

}


/**
 
 Original price of an item whose price a seller has reduced with the Promotional Price
 Display feature.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *originalPrice;

/**
 
 Start time of a discount for an item whose price a seller has reduced with the
 Promotional Price Display feature.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *startTime;

/**
 
 End time of a discount for an item whose price a seller has reduced with the
 Promotional Price Display feature.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *endTime;



@end
