//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
 Shows the pagination of data returned by requests.
 Pagination of returned data is not needed in and not
 supported for every call. See the documentation for
 individual calls to determine whether pagination is
 supported, required, or desirable.
 
 
 @ingroup Trading
*/
@interface Trading_PaginationResultType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *totalNumberOfPages;
    NSNumber *totalNumberOfEntries;

}


/**
 
 Indicates the total number of pages of data
 that could be returned by repeated requests. For
 GetOrders, not applicable to eBay.com (for
 GetOrders, applicable to Half.com). Returned with a
 value of 0 if no pages are available.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalNumberOfPages;

/**
 
 Indicates the total number of entries that
 could be returned by repeated requests. For
 GetOrders, not applicable to eBay.com (for
 GetOrders, applicable to Half.com). Returned with a
 value of 0 if no entries are available.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalNumberOfEntries;



@end
