//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Trading_AbstractRequestType.h"



/**
 
 Returns a list of up to 10 categories that have the highest percentage of listings
 whose titles or descriptions contain the keywords you specify.
 
 
 @ingroup Trading
*/
@interface Trading_GetSuggestedCategoriesRequestType : Trading_AbstractRequestType {

@private
    NSString *query;

}


/**
 
 Specifies the search string, consisting of one or
 more words to search for in the listing title.
 The words "and" and "or" are treated like any other
 word.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *query;


@end
