//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"
#import "Trading_AbstractRequestType.h"


@class Trading_SKUArrayType;
@class Trading_PaginationType;

/**
 
 Retrieves transaction information for the user for which the call is made, and
 not for any other user. (To retrieve transactions for another seller's listings,
 use GetItemTransactions.)
 
 
 @ingroup Trading
*/
@interface Trading_GetSellerTransactionsRequestType : Trading_AbstractRequestType {

@private
    NSDate *modTimeFrom;
    NSDate *modTimeTo;
    Trading_PaginationType *pagination;
    NSNumber *includeFinalValueFee;
    NSNumber *includeContainingOrder;
    Trading_SKUArrayType *skuArray;
    NSString *platform;
    NSNumber *numberOfDays;
    NSString *inventoryTrackingMethod;

}


/**
 
 Also see NumberOfDays, which (if used), takes precedence over ModTimeFrom and
 ModTimeTo. If you prefer to use ModTimeFrom and ModTimeTo, specify the time range
 within which retrieved transactions' statuses were modified. ModTimeFrom is the
 earlier (older) date and ModTimeTo is the later (more recent) date. If you specify
 ModTimeFrom, but do not specify the other end of the range, the time range is set
 to 30 days. The time range between ModTimeFrom to ModTimeTo cannot be greater than
 30 days.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *modTimeFrom;

/**
 
 Also see NumberOfDays, which (if used), takes precedence over ModTimeFrom and
 ModTimeTo. If you prefer to use ModTimeFrom and ModTimeTo, specify the time range
 within which retrieved transactions' statuses were modified. ModTimeFrom is the
 earlier (older) date and ModTimeTo is the later (more recent) date. If you specify
 ModTimeTo, but do not specify the other end of the range, the time range is set to
 30 days. The time range between ModTimeFrom to ModTimeTo cannot be greater than 30
 days.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *modTimeTo;

/**
 
 Child elements control pagination of the output. Use EntriesPerPage property to
 control the number of transactions to return per call and PageNumber property to
 specify the page of data to return.
 
 
 type : class Trading_PaginationType
*/
@property (nonatomic, retain) Trading_PaginationType *pagination;

/**
 
 Indicates whether to include Final Value Fee (FVF) in the response. For most
 listing types, the Final Value Fee is returned in Transaction.FinalValueFee.
 The Final Value Fee is returned on a transaction-by-transaction basis for
 FixedPriceItem and StoresFixedPrice listing types. For all other listing
 types, the Final Value Fee is returned when the listing status is Completed.
 This value is not returned if the auction ended with Buy It Now.
 <br><br>
 For Dutch (multi-item) auctions that end with bids (not Buy It Now
 purchases), the Final Value Fee is returned in
 Item.SellingStatus.FinalValueFee. For Dutch Buy It Now listings, the Final
 Value Fee is returned on a transaction-by-transaction basis.
 <br><br>
 <span class="tablenote"><strong>Note:</strong>
 As of version 619, Dutch-style (multi-item) competitive-bid auctions are
 deprecated. eBay throws an error if you submit a Dutch item listing with AddItem
 or VerifyAddItem. If you use RelistItem to update a Dutch auction listing, eBay
 generates a warning and resets the Quantity value to 1.
 </span>
 <br>
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *includeFinalValueFee;

/**
 
 Whether to retrieve the order information. Default is false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *includeContainingOrder;

/**
 
 Container for a set of SKUs.
 Filters (reduces) the response to only include transactions
 for listings that include any of the specified SKUs.
 If multiple listings include the same SKU, transactions for
 all of them are returned (assuming they also match the other
 criteria in the GetSellerTransactions request).<br>
 <br>
 You can combine SKUArray with InventoryTrackingMethod.
 For example, if you also pass in InventoryTrackingMethod=SKU,
 the response only includes transactions for listings that
 include InventoryTrackingMethod=SKU and one of the
 requested SKUs.
 
 
 type : class Trading_SKUArrayType
*/
@property (nonatomic, retain) Trading_SKUArrayType *skuArray;

/**
 
 Name of the eBay co-branded site upon which the transaction was made.
 This will serve as a filter for the transactions to get emitted in the response.
 
 
 type: string constant in Trading_TransactionPlatformCodeType.h
*/
@property (nonatomic, retain) NSString *platform;

/**
 
 NumberOfDays enables you to specify the number of days' worth of new and modified
 transactions that you want to retrieve. The call response contains the
 transactions whose status was modified within the specified number of days since
 the API call was made. NumberOfDays is often preferable to using the ModTimeFrom
 and ModTimeTo filters because you only need to specify one value. If you use
 NumberOfDays, then ModTimeFrom and ModTimeTo are ignored. For this field, one day
 is defined as 24 hours.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *numberOfDays;

/**
 
 Filters the response to only include transactions for listings
 that match this InventoryTrackingMethod setting. <br>
 <br>
 For example, if you set this to SKU, the call returns
 transactions for your listings that are tracked by SKU.
 If you set this to ItemID, the call omits transactions
 for your listings that are tracked by SKU.
 If you don't pass this in, the call returns all transactions,
 regardless of whether they are tracked by SKU or ItemID.<br>
 <br>
 <span class="tablenote"><b>Note:</b>
 To specify InventoryTrackingMethod when you create a listing,
 use AddFixedPriceItem or RelistFixedPriceItem.
 AddFixedPriceItem and RelistFixedPriceItem are defined in
 the Merchant Data API (part of Large Merchant Services).
 </span>
 <br>
 <br>
 You can combine SKUArray with InventoryTrackingMethod.
 For example, if you set this to SKU and you also pass in
 SKUArray, the response only includes transactions for listings
 that include InventoryTrackingMethod=SKU and one of the
 requested SKUs.
 
 
 type: string constant in Trading_InventoryTrackingMethodCodeType.h
*/
@property (nonatomic, retain) NSString *inventoryTrackingMethod;


@end
