//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 JPG or GIF format.
 
 
 @ingroup Trading
*/

/**
 
 JPG format.
 
*/
extern NSString *const Trading_PictureFormatCodeType_JPG;

/**
 
 GIF format.
 
*/
extern NSString *const Trading_PictureFormatCodeType_GIF;

/**
 
 (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_PictureFormatCodeType_CUSTOM_CODE;
  
