//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AmountType;

/**
 
 Contains the cost of shipping insurance and other insurance-related information.
 
 
 @ingroup Trading
*/
@interface Trading_InsuranceDetailsType : NSObject <EbayNs_Bindable> {

@private
    Trading_AmountType *insuranceFee;
    NSString *insuranceOption;

}


/**
 
 Cost of shipping insurance set by the seller. If the buyer bought more than
 one of this item, this is the insurance for just a single item. Exception:
 for GetItemShipping, this is proportional to QuantitySold. Default is 0.00.
 Value should be greater than 0.00 if InsuranceOption is Optional or Required.
 For flat shipping only. Optional as input and only allowed if
 ChangePaymentInstructions is true.
 <br><br>
 Valid only on the following sites: AU, FR, and IT
 <br />
 Applicable to Half.com (for GetOrders).
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *insuranceFee;

/**
 
 Whether the seller offers shipping insurance and, if so, whether the insurance
 is optional or required. Applies to both flat and calculated shipping.
 Optional as input and only allowed if ChangePaymentInstructions is true.
 <br><br>
 Valid only on the following sites: AU, FR, and IT
 <br />
 Applicable to Half.com (for GetOrders).
 
 
 type: string constant in Trading_InsuranceOptionCodeType.h
*/
@property (nonatomic, retain) NSString *insuranceOption;



@end
