//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_NameValueListType;

/**
 
 A list of one or more valid names and corresponding values. Currently
 used for Item Specifics and Variations.
 
 
 @ingroup Trading
*/
@interface Trading_NameValueListArrayType : NSObject <EbayNs_Bindable> {

@private
    NSMutableArray *nameValueList;

}


/**
 
 <b>For the AddItem family of calls:</b>
 Contains the name and value(s) for an Item Specific.
 Only required when the ItemSpecifics container is
 specified.<br>
 <br>
 <b>For the AddFixedPriceItem family of calls:</b>
 The same NameValueList schema is used for the
 ItemSpecifics node, the VariationSpecifics node, and the
 VariationSpecifcsSet node.<br>
 <br>
 If the listing has varations, any name that you use in the
 VariationSpecifics and VariationSpecificsSet nodes can't be used
 in the ItemSpecifics node.<br>
 <br>
 When you list with Item Variations:<br>
 a) Specify shared Item Specifics (e.g., Brand) in the ItemSpecifics
 node.<br>
 b) Specify up to five VariationSpecifics in each Variation
 node. <br>
 c) Specify all applicable names with all their supported values in
 the VariationSpecificSet node. <br>
 <br>
 See the Variation sample in the
 AddFixedPriceItem call reference for examples.<br>
 <br>
 <b>For PlaceOffer:</b> Required if the item being
 purchased includes Item Variations.
 
 
 entry type : class Trading_NameValueListType
*/
@property (nonatomic, retain) NSMutableArray *nameValueList;


@end
