//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_StoreCustomCategoryArrayType;
@class Trading_StoreThemeType;
@class Trading_StoreLogoType;
@class Trading_StoreCustomListingHeaderType;

/**
 
       The configuration of an eBay Store.
     
 
 @ingroup Trading
*/
@interface Trading_StoreType : NSObject <EbayNs_Bindable> {

@private
    NSString *name;
    NSString *urlPath;
    NSString *url;
    NSString *subscriptionLevel;
    NSString *description;
    Trading_StoreLogoType *logo;
    Trading_StoreThemeType *theme;
    NSString *headerStyle;
    NSNumber *homePage;
    NSString *itemListLayout;
    NSString *itemListSortOrder;
    NSString *customHeaderLayout;
    NSString *customHeader;
    NSNumber *exportListings;
    Trading_StoreCustomCategoryArrayType *customCategories;
    Trading_StoreCustomListingHeaderType *customListingHeader;
    NSString *merchDisplay;
    NSDate *lastOpenedTime;
    NSNumber *titleWithCompatibility;

}


/**
 
 Name of the eBay Store. The name is shown
 at the top of the Store page.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *name;

/**
 
 The URL path of the Store (58 characters maximum). Only if you
 are using Chinese characters in the Name property do you need to
 use this field, such as if you are opening a Store on the Taiwan
 site. The reason for this is that the URL path is normally derived
 from the Store name, but it cannot be derived from the name of the
 Store if it contains Chinese characters because URLs cannot
 contain Chinese characters.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *urlPath;

/**
 
 The complete URL of the user's Store. This field is only ever
 returned, and does not need to be explicitly set.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *url;

/**
 
 Subscription level (tier) for the user's eBay Store.
 
 
 type: string constant in Trading_StoreSubscriptionLevelCodeType.h
*/
@property (nonatomic, retain) NSString *subscriptionLevel;

/**
 
 Store description (300 characters maximum).
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *description;

/**
 
 Store logo.
 
 
 type : class Trading_StoreLogoType
*/
@property (nonatomic, retain) Trading_StoreLogoType *logo;

/**
 
 Store theme.
 
 
 type : class Trading_StoreThemeType
*/
@property (nonatomic, retain) Trading_StoreThemeType *theme;

/**
 
 Style for the Store header.
 
 
 type: string constant in Trading_StoreHeaderStyleCodeType.h
*/
@property (nonatomic, retain) NSString *headerStyle;

/**
 
 Page to use as the Store's homepage (default is 0). To change the
 homepage, specify the PageID of one of the Store's custom pages.
 
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, retain) NSNumber *homePage;

/**
 
 The default layout type to use for the Store items.
 
 
 type: string constant in Trading_StoreItemListLayoutCodeType.h
*/
@property (nonatomic, retain) NSString *itemListLayout;

/**
 
 The default sort order to use for the items for sale in the Store.
 
 
 type: string constant in Trading_StoreItemListSortOrderCodeType.h
*/
@property (nonatomic, retain) NSString *itemListSortOrder;

/**
 
 Layout for the Store's custom header.
 
 
 type: string constant in Trading_StoreCustomHeaderLayoutCodeType.h
*/
@property (nonatomic, retain) NSString *customHeaderLayout;

/**
 
 Custom header text for the Store.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *customHeader;

/**
 
 Specifies whether to export the Store listings to comparison
 shopping websites.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *exportListings;

/**
 
 Custom categories for the Store. Deprecated (input ignored) for SetStore
 with request version 449 or higher. Use SetStoreCategories with
 request verison 449 or higher to modify store category structures.
 
 
 type : class Trading_StoreCustomCategoryArrayType
*/
@property (nonatomic, retain) Trading_StoreCustomCategoryArrayType *customCategories;

/**
 
 Custom listing header for the Store.
 
 
 type : class Trading_StoreCustomListingHeaderType
*/
@property (nonatomic, retain) Trading_StoreCustomListingHeaderType *customListingHeader;

/**
 
 Specifies the chosen customization display scheme for this store's Merch Widgets.
 See MerchDisplayCodeType for specific values.
 
 
 type: string constant in Trading_MerchDisplayCodeType.h
*/
@property (nonatomic, retain) NSString *merchDisplay;

/**
 
 Indicates the time the store was last opened or reopened.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *lastOpenedTime;

/**
 
 For item listings that have parts compatibility information, eBay Store
 sellers can specify whether or not compatibilitly information, such as
 compatible vehichle make and model are displayed, in addition to the item
 title, within store searches. This does not affect the item title itself.
 <br><br>
 Parts Compatibility is supported in limited Parts & Accessories categories
 for the eBay Motors (US) site (site ID 100) only.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *titleWithCompatibility;



@end
