//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Codes indicate the address type.
 
 
 @ingroup Trading
*/

extern NSString *const Trading_AddressRecordTypeCodeType_RESIDENTIAL;

extern NSString *const Trading_AddressRecordTypeCodeType_BUSINESS;

/**
 
 (out) Reserved for internal or future use
 
*/
extern NSString *const Trading_AddressRecordTypeCodeType_CUSTOM_CODE;
  
