//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_AmountType;

/**
 
 Contains summary information about the items the seller is selling.
 
 
 @ingroup Trading
*/
@interface Trading_MyeBaySellingSummaryType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *activeAuctionCount;
    NSNumber *auctionSellingCount;
    NSNumber *auctionBidCount;
    Trading_AmountType *totalAuctionSellingValue;
    NSNumber *totalSoldCount;
    Trading_AmountType *totalSoldValue;
    NSNumber *soldDurationInDays;
    NSNumber *classifiedAdCount;
    NSNumber *totalLeadCount;
    NSNumber *classifiedAdOfferCount;
    NSNumber *totalListingsWithLeads;

}


/**
 
 The number of currently active auctions that will sell. That
 is, there is at least one bidder, and any reserve price has
 been met. Equivalent to the "Will Sell" value in My eBay.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *activeAuctionCount;

/**
 
 The total number of currently active auctions for a given
 seller. Note that this does not include listings that are
 FixedPriceItem or StoresFixedPrice. Equivalent to the
 "Auction Quantity" value in My eBay.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *auctionSellingCount;

/**
 
 The total number of bids made on the seller's active listings.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *auctionBidCount;

/**
 
 For all items that the seller has for sale, the total
 selling values of those items having bids and where the
 Reserve price is met (if a Reserve price is specified).
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *totalAuctionSellingValue;

/**
 
 The total number of items that the seller has sold in the
 past 31 days.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalSoldCount;

/**
 
 The total monetary value of the items the seller has sold.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *totalSoldValue;

/**
 
 The average duration, in days, of all items sold.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *soldDurationInDays;

/**
 
 The total number of classified ad listings listed by the
 seller.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *classifiedAdCount;

/**
 
 The total number of leads from the seller's classified
 ad listings. Number indicates the total number of emails
 received for the listings
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalLeadCount;

/**
 
 The total number of offers received on active Classified
 Ad listings.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *classifiedAdOfferCount;

/**
 
 The total number of Classified Ad listings that have an
 associated lead.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *totalListingsWithLeads;



@end
