//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"


@class Trading_ListingEnhancementDurationReferenceType;
@class Trading_StoreOwnerExtendedListingDurationsType;
@class Trading_ListingDurationReferenceType;
@class Trading_ConditionValuesType;
@class Trading_AmountType;

/**
 
 A container node that identifies a category that has one of the features
 specified in FeatureID (in GetCategoryFeaturesRequest).
 
 
 @ingroup Trading
*/
@interface Trading_CategoryFeatureType : NSObject <EbayNs_Bindable> {

@private
    NSString *categoryID;
    NSMutableArray *listingDuration;
    NSNumber *shippingTermsRequired;
    NSNumber *bestOfferEnabled;
    NSNumber *dutchBINEnabled;
    NSNumber *userConsentRequired;
    NSNumber *homePageFeaturedEnabled;
    NSNumber *proPackEnabled;
    NSNumber *basicUpgradePackEnabled;
    NSNumber *valuePackEnabled;
    NSNumber *proPackPlusEnabled;
    NSString *adFormatEnabled;
    NSNumber *bestOfferCounterEnabled;
    NSNumber *bestOfferAutoDeclineEnabled;
    NSNumber *localMarketSpecialitySubscription;
    NSNumber *localMarketRegularSubscription;
    NSNumber *localMarketPremiumSubscription;
    NSNumber *localMarketNonSubscription;
    NSNumber *expressEnabled;
    NSNumber *expressPicturesRequired;
    NSNumber *expressConditionRequired;
    NSNumber *minimumReservePrice;
    NSNumber *sellerContactDetailsEnabled;
    NSNumber *transactionConfirmationRequestEnabled;
    NSNumber *storeInventoryEnabled;
    NSNumber *skypeMeTransactionalEnabled;
    NSNumber *skypeMeNonTransactionalEnabled;
    NSString *classifiedAdPaymentMethodEnabled;
    NSNumber *classifiedAdShippingMethodEnabled;
    NSString *classifiedAdBestOfferEnabled;
    NSNumber *classifiedAdCounterOfferEnabled;
    NSNumber *classifiedAdAutoDeclineEnabled;
    NSNumber *classifiedAdContactByPhoneEnabled;
    NSNumber *classifiedAdContactByEmailEnabled;
    NSNumber *safePaymentRequired;
    NSNumber *classifiedAdPayPerLeadEnabled;
    NSString *itemSpecificsEnabled;
    NSNumber *paisaPayFullEscrowEnabled;
    NSNumber *classifiedAdAutoAcceptEnabled;
    NSNumber *bestOfferAutoAcceptEnabled;
    NSNumber *crossBorderTradeNorthAmericaEnabled;
    NSNumber *crossBorderTradeGBEnabled;
    NSNumber *crossBorderTradeAustraliaEnabled;
    NSNumber *payPalBuyerProtectionEnabled;
    NSNumber *buyerGuaranteeEnabled;
    NSNumber *combinedFixedPriceTreatmentEnabled;
    Trading_ListingEnhancementDurationReferenceType *galleryFeaturedDurations;
    NSNumber *payPalRequired;
    NSString *eBayMotorsProAdFormatEnabled;
    NSNumber *eBayMotorsProContactByPhoneEnabled;
    NSNumber *eBayMotorsProPhoneCount;
    NSNumber *eBayMotorsProContactByAddressEnabled;
    NSNumber *eBayMotorsProStreetCount;
    NSNumber *eBayMotorsProCompanyNameEnabled;
    NSNumber *eBayMotorsProContactByEmailEnabled;
    NSString *eBayMotorsProBestOfferEnabled;
    NSNumber *eBayMotorsProAutoAcceptEnabled;
    NSNumber *eBayMotorsProAutoDeclineEnabled;
    NSString *eBayMotorsProPaymentMethodCheckOutEnabled;
    NSNumber *eBayMotorsProShippingMethodEnabled;
    NSNumber *eBayMotorsProCounterOfferEnabled;
    NSNumber *eBayMotorsProSellerContactDetailsEnabled;
    NSString *localMarketAdFormatEnabled;
    NSNumber *localMarketContactByPhoneEnabled;
    NSNumber *localMarketPhoneCount;
    NSNumber *localMarketContactByAddressEnabled;
    NSNumber *localMarketStreetCount;
    NSNumber *localMarketCompanyNameEnabled;
    NSNumber *localMarketContactByEmailEnabled;
    NSString *localMarketBestOfferEnabled;
    NSNumber *localMarketAutoAcceptEnabled;
    NSNumber *localMarketAutoDeclineEnabled;
    NSString *localMarketPaymentMethodCheckOutEnabled;
    NSNumber *localMarketShippingMethodEnabled;
    NSNumber *localMarketCounterOfferEnabled;
    NSNumber *localMarketSellerContactDetailsEnabled;
    NSNumber *classifiedAdPhoneCount;
    NSNumber *classifiedAdContactByAddressEnabled;
    NSNumber *classifiedAdStreetCount;
    NSNumber *classifiedAdCompanyNameEnabled;
    NSString *specialitySubscription;
    NSString *regularSubscription;
    NSString *premiumSubscription;
    NSString *nonSubscription;
    NSString *inEscrowWorkflowTimeline;
    NSNumber *payPalRequiredForStoreOwner;
    NSNumber *reviseQuantityAllowed;
    NSNumber *revisePriceAllowed;
    NSNumber *storeOwnerExtendedListingDurationsEnabled;
    Trading_StoreOwnerExtendedListingDurationsType *storeOwnerExtendedListingDurations;
    NSNumber *returnPolicyEnabled;
    NSNumber *handlingTimeEnabled;
    Trading_AmountType *maxFlatShippingCost;
    Trading_AmountType *group1MaxFlatShippingCost;
    Trading_AmountType *group2MaxFlatShippingCost;
    Trading_AmountType *group3MaxFlatShippingCost;
    NSMutableArray *paymentMethod;
    NSNumber *variationsEnabled;
    NSString *attributeConversionEnabled;
    NSNumber *freeGalleryPlusEnabled;
    NSNumber *freePicturePackEnabled;
    NSString *itemCompatibilityEnabled;
    NSNumber *minItemCompatibility;
    NSNumber *maxItemCompatibility;
    NSString *conditionEnabled;
    Trading_ConditionValuesType *conditionValues;

}


/**
 
 Specifies the identifier of the category that has the feature.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *categoryID;

/**
 
   Identifies the listing duration set that applies to the category.
 
 
 entry type : class Trading_ListingDurationReferenceType
*/
@property (nonatomic, retain) NSMutableArray *listingDuration;

/**
 
 Indicates whether sellers are required to specify shipping items
 for this category. Returned only if this category overrides the
 site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *shippingTermsRequired;

/**
 
   Indicates whether best offers is allowed for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *bestOfferEnabled;

/**
 
   Indicates whether Buy It Now is allowed in this category for Dutch (multi-item)
 auctions. Returned only if this category overrides the site default.
 <br><br>
 <span class="tablenote"><strong>Note:</strong>
 As of version 619, Dutch-style (multi-item) competitive-bid auctions are deprecated.
 eBay throws an error if you submit a Dutch item listing with AddItem
 or VerifyAddItem. If you use RelistItem to update a Dutch auction listing,
 eBay generates a warning and resets the Quantity value to 1.
 </span>
 <br>
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *dutchBINEnabled;

/**
 
   Indicates whether a bidder must consent to the bid by confirming that
   he or she read and agrees to the terms in eBay's privacy policy.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *userConsentRequired;

/**
 
   Indicates whether or not it is possible to enhance a listing by putting
 it into a rotation for display on a special area of the eBay home page.
 Support for this feature varies by site. Item or feedback restrictions may apply.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *homePageFeaturedEnabled;

/**
 
 Indicates whether ProPackBundle (a feature pack) is enabled for this category.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *proPackEnabled;

/**
 
 Not applicable to any site.
 Indicated whether the Basic Upgrade Pack bundle feature
 was enabled for this category. Formerly, Australia site
 (site ID 15, abbreviation AU) only.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *basicUpgradePackEnabled;

/**
 
 Indicates whether ValuePack bundle (a feature pack) is enabled
 for this category.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *valuePackEnabled;

/**
 
 Indicates whether the ProPackPlus bundle (a feature pack) is enabled for this category.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *proPackPlusEnabled;

/**
 
 Indicates whether the Classified Ad format feature is enabled for this
 category.
 
 
 type: string constant in Trading_AdFormatEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *adFormatEnabled;

/**
 
 Indicates whether counter offers are allowed on best offers for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *bestOfferCounterEnabled;

/**
 
 Indicates whether auto decline for best offers is allowed for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *bestOfferAutoDeclineEnabled;

/**
 
 Indicates whether LocalMarketSpecialitySubscription feature is supported for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketSpecialitySubscription;

/**
 
 Indicates whether LocalMarketRegularSubscription feature is supported for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketRegularSubscription;

/**
 
 Indicates whether LocalMarketPremiumSubscription feature is supported for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketPremiumSubscription;

/**
 
 Indicates whether LocalMarketNonSubscription feature is supported for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketNonSubscription;

/**
 
 Indicates whether listings in this category are eligible for eBay Express
 (assuming other item and user eligibility requirements are also met).
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *expressEnabled;

/**
 
 Indicates whether a listing requires a picture (or gallery image) in order
 to qualify for eBay Express when listed in this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *expressPicturesRequired;

/**
 
 Indicates whether a listing requires the Item Condition
 to be specified (using Item Specifics in AttributeSetArray) in order
 to qualify for eBay Express when listed in this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *expressConditionRequired;

/**
 
 Indicates whether Minimum Reserve Price is enabled for this category. Returned only
 if this category overrides the site default. On the Germany, Austria, Belgium French,
 and Belgium Dutch sites, Minimum Reserve Price is supported for the Art and Antiques,
 Watches and Jewelry, and Motorbikes categories.
 
 
 type : NSNumber, wrapper for primitive double
*/
@property (nonatomic, retain) NSNumber *minimumReservePrice;

/**
 
 Indicates whether this category supports seller-level contact information for
 Classified Ad format listings. Returned only if this category overrides the
 site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *sellerContactDetailsEnabled;

/**
 
 Indicates whether the Transaction Confirmation Request feature is supported for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *transactionConfirmationRequestEnabled;

/**
 
 Indicates whether Store Inventory Format is enabled for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *storeInventoryEnabled;

/**
 
 Indicates whether the addition of Skype buttons to listings is supported for this category for transactional formats (e.g., the Chinese auction format).
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *skypeMeTransactionalEnabled;

/**
 
 Indicates whether the addition of Skype buttons to listings is supported
 for this category for non-transactional formats (e.g., the advertisement format).
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *skypeMeNonTransactionalEnabled;

/**
 
 Indicates whether the payment method should be displayed to the user for
 Classified Ad format listings.
 Even if enabled, checkout may or may not be enabled.
 
 
 type: string constant in Trading_ClassifiedAdPaymentMethodEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *classifiedAdPaymentMethodEnabled;

/**
 
 Indicates if shipping options are available for Classified Ad listings
 in the category. Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *classifiedAdShippingMethodEnabled;

/**
 
 Indicates if Best offer is enabled for Classified Ad listings.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_ClassifiedAdBestOfferEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *classifiedAdBestOfferEnabled;

/**
 
 Indicates whether counter offers are allowed on Classified Ad listings
 for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *classifiedAdCounterOfferEnabled;

/**
 
 Indicates whether automatic decline for best offers for Classified Ad listings is allowed for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *classifiedAdAutoDeclineEnabled;

/**
 
 Indicates whether the telephone is supported as a contact method for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *classifiedAdContactByPhoneEnabled;

/**
 
 Indicates whether the category supports email as a contact method.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *classifiedAdContactByEmailEnabled;

/**
 
 Indicates whether listings in this category need to have a safe
 payment method, for all sellers registered after January 17,2007.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *safePaymentRequired;

/**
 
 Indicates if pay-per-lead listings are allowed for this category.
 Pay-per-lead listings can be applicable if the ListingType is
 LeadGeneration and the ListingSubtype is ClassifiedAd.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *classifiedAdPayPerLeadEnabled;

/**
 
 Indicates whether the category supports custom Item Specifics.
 If enabled, sellers can use the Item.ItemSpecifics node in AddItem
 and related calls to fill in Item Specifics. If your application
 supports the older ID-based Attribute format, also see
 AttributeConversionEnabled to determine whether or not you may
 need to suppress ID-based attributes for the category.
 
 
 type: string constant in Trading_ItemSpecificsEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *itemSpecificsEnabled;

/**
 
 Indicates whether the category supports the PaisaPayEscrow payment method.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *paisaPayFullEscrowEnabled;

/**
 
 Indicates whether the category supports setting
 a price at which best offers are automatically accepted
 for Classified Ads.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *classifiedAdAutoAcceptEnabled;

/**
 
 Indicates whether the category supports setting
 a price at which best offers are automatically accepted.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *bestOfferAutoAcceptEnabled;

/**
 
 Indicates whether the category supports specifying that listings be displayed in the default search results of North America sites.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *crossBorderTradeNorthAmericaEnabled;

/**
 
 Indicates whether the category supports specifying that listings
 be displayed in the default search results of the UK site.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *crossBorderTradeGBEnabled;

/**
 
 Indicates whether the category supports specifying that listings be displayed in the default search results of the Australia site.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *crossBorderTradeAustraliaEnabled;

/**
 
 For the Australia site, if both PayPalBuyerProtectionEnabled
 and BuyerGuaranteeEnabled are returned, then
 buyer protection is allowed for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *payPalBuyerProtectionEnabled;

/**
 
 For the Australia site, if both PayPalBuyerProtectionEnabled
 and BuyerGuaranteeEnabled are returned, then
 buyer protection is allowed for this category.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *buyerGuaranteeEnabled;

/**
 
 Indicates whether the category supports
 combined fixed price treatment for the following two listing
 types: Store Inventory Format and Basic Fixed Price.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *combinedFixedPriceTreatmentEnabled;

/**
 
 Indicates whether the category supports
 durations for "Gallery Featured".
 Returned only if this category overrides the site default.
 
 
 type : class Trading_ListingEnhancementDurationReferenceType
*/
@property (nonatomic, retain) Trading_ListingEnhancementDurationReferenceType *galleryFeaturedDurations;

/**
 
 Indicates whether the category requires PayPal as a payment method.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *payPalRequired;

/**
 
 Specifies whether this category allows Classified Ad listings.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_AdFormatEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *eBayMotorsProAdFormatEnabled;

/**
 
 Indicates whether this category supports including the telephone in the
 seller's contact information.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProContactByPhoneEnabled;

/**
 
 Indicates which telephone option is enabled for the seller's contact information.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProPhoneCount;

/**
 
 Indicates whether this category supports including the address in the
 seller's contact information.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProContactByAddressEnabled;

/**
 
 Indicates which address option is enabled for the seller's contact information.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProStreetCount;

/**
 
 Indicates whether this category supports including the company name in the
 seller's contact information.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProCompanyNameEnabled;

/**
 
 Indicates whether this category supports including an email address in the
 seller's contact information.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProContactByEmailEnabled;

/**
 
 Indicates if Best Offer is supported for Classified Ad listings
 in this category.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_ClassifiedAdBestOfferEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *eBayMotorsProBestOfferEnabled;

/**
 
 Specifies whether this category allows
 auto-accept for Best Offers for Classified Ads.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProAutoAcceptEnabled;

/**
 
 Specifies whether this category allows
 auto-decline for Best Offers for Classified Ads.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProAutoDeclineEnabled;

/**
 
 Indicates if the payment method should be displayed to the user
 for this category. Even if enabled, checkout may or may not
 be enabled.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_ClassifiedAdPaymentMethodEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *eBayMotorsProPaymentMethodCheckOutEnabled;

/**
 
 Indicates if shipping options are available for this category.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProShippingMethodEnabled;

/**
 
 Indicates whether counter offers are allowed on Best Offers for
 this category.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProCounterOfferEnabled;

/**
 
 Specifies whether this category allows seller-level contact information for Classified Ad listings. A value of true
 means seller-level contact information is available for Classified Ad listings.
 This element is for eBay Motors Pro users.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayMotorsProSellerContactDetailsEnabled;

/**
 
 Specifies whether this category supports Classified Ad listings.
 This is added for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_AdFormatEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *localMarketAdFormatEnabled;

/**
 
 Indicates whether this category supports including a telephone number in the
 seller's contact information.
 This element is added for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketContactByPhoneEnabled;

/**
 
 Indicates which telephone option is enabled for the seller's contact information.
 This element is for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *localMarketPhoneCount;

/**
 
 Indicates whether the category supports including an address in the
 seller's contact information.
 This element is for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketContactByAddressEnabled;

/**
 
 Indicates which address option for is included in the
 seller's contact information.
 This element is for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *localMarketStreetCount;

/**
 
 Indicates whether the category supports including a company name in the
 seller's contact information.
 This element is for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketCompanyNameEnabled;

/**
 
 Indicates whether the category supports including an email address in the
 seller's contact information.
 This element is for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketContactByEmailEnabled;

/**
 
 Indicates if Best Offer is enabled for Classified Ad listings
 in this category.
 This element is for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_ClassifiedAdBestOfferEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *localMarketBestOfferEnabled;

/**
 
 Specifies whether this category supports auto-accept for best offers for Classified Ads.
 This element is for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketAutoAcceptEnabled;

/**
 
 Specifies whether this category supports auto-decline for best offers for Classified Ads.
 This element is for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketAutoDeclineEnabled;

/**
 
 Indicates if the payment method should be displayed to the user
 for this category. Even if enabled, checkout may or may not
 be enabled.
 This element is for Local Market dealers.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_ClassifiedAdPaymentMethodEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *localMarketPaymentMethodCheckOutEnabled;

/**
 
 Indicates if shipping options are available for this category.
 This element is for Local market dealers.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketShippingMethodEnabled;

/**
 
 Indicates whether counter offers are allowed on best offers for
 this category.
 This element is for Local market dealers.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketCounterOfferEnabled;

/**
 
 Specifies the whether this category allows
 seller-level contact information for Classified Ad listings.
 This element is for Local Market dealers.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *localMarketSellerContactDetailsEnabled;

/**
 
 Indicates which telephone option is included in the
 seller's contact information.
 This element is for For Sale By Owner listings.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *classifiedAdPhoneCount;

/**
 
 Indicates whether this category supports including an address in the
 seller's contact information.
 This element is for For Sale By Owner listings.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *classifiedAdContactByAddressEnabled;

/**
 
 Indicates which address option is included in the
 seller's contact information.
 This element is for For Sale By Owner listings.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *classifiedAdStreetCount;

/**
 
 Indicates whether this category supports including a company name in the
 seller's contact information.
 This element is for For Sale By Owner listings.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *classifiedAdCompanyNameEnabled;

/**
 
 Specifies this speciality subscription feature for
 this category.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_GeographicExposureCodeType.h
*/
@property (nonatomic, retain) NSString *specialitySubscription;

/**
 
 Specifies the regular lsubscription feature that is supported for
 this category.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_GeographicExposureCodeType.h
*/
@property (nonatomic, retain) NSString *regularSubscription;

/**
 
 Specifies the premium subscription feature for this category.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_GeographicExposureCodeType.h
*/
@property (nonatomic, retain) NSString *premiumSubscription;

/**
 
 Specifies the supported local listing distances for this category,
 for users who have not subscribed to either Regular or Specialty vehicles.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_GeographicExposureCodeType.h
*/
@property (nonatomic, retain) NSString *nonSubscription;

/**
 
 Indicates the escrow workflow version that applies to the category on the
 India site: Default Workflow, Workflow A or Workflow B.
 Returned only if this category overrides the site default.
 
 
 type: string constant in Trading_INEscrowWorkflowTimelineCodeType.h
*/
@property (nonatomic, retain) NSString *inEscrowWorkflowTimeline;

/**
 
 Defines if PayPal is required for Store Owner listings in this category.
 Applies to Fixed Price Listings as well as Store Inventory Format listings.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *payPalRequiredForStoreOwner;

/**
 
 If true, the item quantity for listings in this category can be revised
 while the listing is in semi or fully restricted mode.
 Applies to Fixed Price Listings as well as Store Inventory Format listings.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *reviseQuantityAllowed;

/**
 
 If true, the start price for items in this category can be revised while the
 listing is in semi or fully restricted mode.
 Applies to Fixed Price Listings as well as Store Inventory Format listings.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *revisePriceAllowed;

/**
 
 Defines if extended store owner listing durations are enabled in a given category.
 When the value of this element is true, it means the listing duration values
 defined in StoreOwnerExtendedListingDurations are applicable to fixed price
 listings in a given category.
 Applies to Fixed Price Listings as well as Store Inventory Format listings.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *storeOwnerExtendedListingDurationsEnabled;

/**
 
 Provides additional listings durations that are supported by Store Ownwers.
 The extended listing durations provided here in this element should be merged
 in with the baseline listing durations provided in the ListingDurations element.
 Applies to Fixed Price Listings as well as Store Inventory Format listings.
 
 
 type : class Trading_StoreOwnerExtendedListingDurationsType
*/
@property (nonatomic, retain) Trading_StoreOwnerExtendedListingDurationsType *storeOwnerExtendedListingDurations;

/**
 
 <b>For most sites:</b> If true, listings in this 
 category require a return policy. <br>
 <br>
 <b>For eBay India (IN), Australia (AU), and 
 US eBay Motors Parts and Accessories:</b> 
 If true, the category supports but does not require a 
 return policy.<br>
 <br>
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *returnPolicyEnabled;

/**
 
 If false, listings in this category require a handling time
 (see DispatchTimeMax in AddItem) when flat or calculated shipping
 is specified. (A handling time is not required for local pickup
 or for freight shipping.)<br>
 <br>
 The handling time is the maximum number of business days the seller
 commits to for preparing an item to be shipped after receiving a
 cleared payment. The seller's handling time does not include the
 shipping time (the carrier's transit time).<br>
 <br>
 Returned only if this category overrides the site default.<br>
 <br>
 For a list of the handling time values allowed for each site, use
 DispatchTimeMaxDetails in GeteBayDetails.<br>
 <br>
 <span class="tablenote"><b>Note:</b>
 Although the field name ends with "Enabled", a value of true means
 that a handling time is NOT supported, and value of false means
 that a handling time IS supported.</span>
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *handlingTimeEnabled;

/**
 
 The maximum cost the seller can charge for the first domestic flat rate shipping
 service. The total shipping cost is the seller's base flat rate
 shipping cost plus the cost of insurance, if insurance is required.
 Only returned if MaxFlatShippingCostEnabled is true.
 Mutually exclusive with the GroupNMaxFlatShippingCost elements.
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *maxFlatShippingCost;

/**
 
 Returns the applicable max cap per shipping cost for shipping service group1
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *group1MaxFlatShippingCost;

/**
 
 Returns the applicable max cap per shipping cost for shipping service group2
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *group2MaxFlatShippingCost;

/**
 
 Returns the applicable max cap per shipping cost for shipping service group3
 
 
 type : class Trading_AmountType
*/
@property (nonatomic, retain) Trading_AmountType *group3MaxFlatShippingCost;

/**
 
 Indicates the acceptable payment methods.
 
 
 entry type : string constant in Trading_BuyerPaymentMethodCodeType.h
*/
@property (nonatomic, retain) NSMutableArray *paymentMethod;

/**
 
 If true, you can pass in Item.Variations in the
 AddFixedPriceItem family of calls when you list in this
 category.<br>
 <br>
 Multi-variation listings contain items that are logically the same
 product, but that vary in their manufacturing details or packaging.
 For example, a particular brand and style of shirt could be
 available in different sizes and colors, such as "large blue" and
 "medium black" variations.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *variationsEnabled;

/**
 
 Indicates whether eBay has converted the category from
 ID-based attributes to custom Item Specifics.
 Only applicable to categories that previously supported
 ID-based attributes. If conversion is Enabled or Disabled,
 we recommend that you avoid rendering ID-based attributes and
 custom Item Specifics together for items in that category
 (to avoid displaying the same Item Specifics twice).<br>
 <br>
 If conversion is Enabled or Disabled and the category is flagged as
 CatalogEnabled in GetCategory2CS,
 you can use GetItemRecommendations to retrieve product details
 in the custom Item Specifics format instead of using
 GetProductSellingPages to retrieve product details in the
 ID-based attributes format.<br>
 <br>
 With version 607 and lower, categories with attribute conversion
 Enabled or Disabled do not return recommendations in
 GetCategorySpecifics.
 
 
 type: string constant in Trading_AttributeConversionEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *attributeConversionEnabled;

/**
 
 Indicates whether the category supports
 free, automatic upgrades for Gallery Plus, which
 enhances pictures in search results.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *freeGalleryPlusEnabled;

/**
 
 Indicates whether the category supports
 free, automatic upgrades for Picture Pack, a discount
 package that includes super-sizing of pictures.
 Returned only if this category overrides the site default.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *freePicturePackEnabled;

/**
 
 Indicates whether the category supports parts compatibility by application
 (ByApplication), by specification (BySpecification), or not at all
 (Disabled). Categories cannot support both types of parts compatibility.
 <br><br> 
 Parts Compatibility is supported in limited Parts & Accessories
 categories for the eBay Motors (US) site (site ID 100) only.
 
 
 type: string constant in Trading_ItemCompatibilityEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *itemCompatibilityEnabled;

/**
 
 This field specifies the minimum number of required compatible applications
 for listing items. A value of "0" indicates it is not mandatory to specify
 parts compatibilities when listing. 
 <br><br> 
 This applies to categories that are enabled for compatibility by application
 only. Parts compatiblity by application can be specified by listing with a
 catalog product that supports parts compatibility or by specifying parts
 compatibility by application manually (<b class="con">
 Item.ItemCompatibilityList</b>).
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *minItemCompatibility;

/**
 
 This field specifies the maximum number of compatible applications allowed
 per item when adding or revising items. This is relevant for specifying parts
 compatibility by application manually (<b class="con">
 Item.ItemCompatibilityList</b>) only.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *maxItemCompatibility;

/**
 
 Indicates whether the category supports (or requires) 
 using Item.ConditionID to specify an item's condition 
 in AddItem and related calls. See ConditionValues for 
 a list of valid IDs.<br>
 <br>
 <span class="tablenote"><b>Note:</b>
 Some categories may still support using the older Attribute model
 and/or Custom Item Specifics model for item condition.
 If ConditionEnabled=Enabled (or Required) for a category, 
 you should stop using these other fields to specify the condition
 in your listings.
 </span>
 
 
 type: string constant in Trading_ConditionEnabledCodeType.h
*/
@property (nonatomic, retain) NSString *conditionEnabled;

/**
 
 Specifies the supported item conditions for the category, 
 plus related policies and other details.
 Only returned if ConditionEnabled is Enabled or Required
 for the category (and the condition values are different than the 
 site defaults).
 
 
 type : class Trading_ConditionValuesType
*/
@property (nonatomic, retain) Trading_ConditionValuesType *conditionValues;



@end
