//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
   The type of promotion.
 
 
 @ingroup Trading
*/

/**
 
 Promote/present items that are related to or can be used with the
 specified item.
 
*/
extern NSString *const Trading_PromotionMethodCodeType_CROSS_SELL;

/**
 
 Promote/present items that of higher quality or more expensive
 than the specified item.
 
*/
extern NSString *const Trading_PromotionMethodCodeType_UP_SELL;

/**
 
 Reserved for internal or future use.
 
*/
extern NSString *const Trading_PromotionMethodCodeType_CUSTOM_CODE;
  
