//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Specifies whether the Store has a custom header.
 
 
 @ingroup Trading
*/

/**
 
 Specifies that the Store does not have a custom header.
 
*/
extern NSString *const Trading_StoreCustomHeaderLayoutCodeType_NO_HEADER;

/**
 
 Specifies that the Store does have a custom header.
 
*/
extern NSString *const Trading_StoreCustomHeaderLayoutCodeType_CUSTOM_HEADER_SHOWN;

/**
 
    (out) Reserved for internal or future use.
 
*/
extern NSString *const Trading_StoreCustomHeaderLayoutCodeType_CUSTOM_CODE;
  
