//
// Generated by eBay Common SDK Platform
//

#import <Foundation/Foundation.h>

/**
 @file
 
 Combined Purchase Options
 
 
 @ingroup Trading
*/

/**
 
 No Combined Purchase
 
*/
extern NSString *const Trading_CombinedPaymentOptionCodeType_NO_COMBINED_PAYMENT;

/**
 
 Yes Specify Discount Now
 
*/
extern NSString *const Trading_CombinedPaymentOptionCodeType_DISCOUNT_SPECIFIED;

/**
 
 Yes Specify Discount Later
 
*/
extern NSString *const Trading_CombinedPaymentOptionCodeType_SPECIFY_DISCOUNT_LATER;

/**
 
 Reserved for internal or future use
 
*/
extern NSString *const Trading_CombinedPaymentOptionCodeType_CUSTOM_CODE;
  
