//
// Generated by eBay Common SDK Platform, DO NOT CHANGE!
//

#import <Foundation/Foundation.h>
#import "EbayNs_ClassSchema.h"
#import "EbayNs_PropertySchema.h"
#import "EbayNs_BindingConstant.h"
#import "EbayNs_Bindable.h"



/**
 
  DistanceType used in proximity search
 
 
 @ingroup Trading
*/
@interface Trading_DistanceType : NSObject <EbayNs_Bindable> {

@private
    NSNumber *distanceMeasurement;
    NSString *distanceUnit;

}


/**
 
 The measurement used in a proximity search distance calculation.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *distanceMeasurement;

/**
 
 The unit used in a proximity search distance calculation.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *distanceUnit;



@end
